# continents source: https://pypi.org/project/pycountry-convert/
COUNTRIES_BY_REGION = {
    "Africa": [
        {"name": "Algeria", "country_code": "DZ"},
        {"name": "Angola", "country_code": "AO"},
        {"name": "Benin", "country_code": "BJ"},
        {"name": "Botswana", "country_code": "BW"},
        {"name": "Burkina Faso", "country_code": "BF"},
        {"name": "Burundi", "country_code": "BI"},
        {"name": "Cameroon", "country_code": "CM"},
        {"name": "Cabo Verde", "country_code": "CV"},
        {"name": "Central African Republic", "country_code": "CF"},
        {"name": "Chad", "country_code": "TD"},
        {"name": "Comoros", "country_code": "KM"},
        {"name": "Congo", "country_code": "CG"},
        {"name": "Congo, Democratic Republic of the", "country_code": "CD"},
        {"name": "Côte d'Ivoire", "country_code": "CI"},
        {"name": "Djibouti", "country_code": "DJ"},
        {"name": "Egypt", "country_code": "EG"},
        {"name": "Equatorial Guinea", "country_code": "GQ"},
        {"name": "Eritrea", "country_code": "ER"},
        {"name": "Ethiopia", "country_code": "ET"},
        {"name": "Gabon", "country_code": "GA"},
        {"name": "Gambia", "country_code": "GM"},
        {"name": "Ghana", "country_code": "GH"},
        {"name": "Guinea", "country_code": "GN"},
        {"name": "Guinea-Bissau", "country_code": "GW"},
        {"name": "Kenya", "country_code": "KE"},
        {"name": "Lesotho", "country_code": "LS"},
        {"name": "Liberia", "country_code": "LR"},
        {"name": "Libya", "country_code": "LY"},
        {"name": "Madagascar", "country_code": "MG"},
        {"name": "Malawi", "country_code": "MW"},
        {"name": "Mali", "country_code": "ML"},
        {"name": "Mauritania", "country_code": "MR"},
        {"name": "Mauritius", "country_code": "MU"},
        {"name": "Mayotte", "country_code": "YT"},
        {"name": "Morocco", "country_code": "MA"},
        {"name": "Mozambique", "country_code": "MZ"},
        {"name": "Namibia", "country_code": "NA"},
        {"name": "Niger", "country_code": "NE"},
        {"name": "Nigeria", "country_code": "NG"},
        {"name": "Réunion", "country_code": "RE"},
        {"name": "Rwanda", "country_code": "RW"},
        {"name": "Saint Helena, Ascension and Tristan da Cunha", "country_code": "SH"},
        {"name": "Sao Tome and Principe", "country_code": "ST"},
        {"name": "Senegal", "country_code": "SN"},
        {"name": "Seychelles", "country_code": "SC"},
        {"name": "Sierra Leone", "country_code": "SL"},
        {"name": "Somalia", "country_code": "SO"},
        {"name": "South Africa", "country_code": "ZA"},
        {"name": "South Sudan", "country_code": "SS"},
        {"name": "Sudan", "country_code": "SD"},
        {"name": "Eswatini", "country_code": "SZ"},
        {"name": "Tanzania, United Republic of", "country_code": "TZ"},
        {"name": "Togo", "country_code": "TG"},
        {"name": "Tunisia", "country_code": "TN"},
        {"name": "Uganda", "country_code": "UG"},
        {"name": "Zambia", "country_code": "ZM"},
        {"name": "Zimbabwe", "country_code": "ZW"},
    ],
    "Antarctica": [
        {"name": "Antarctica", "country_code": "AQ"},
        {"name": "Bouvet Island", "country_code": "BV"},
        {"name": "Heard Island and McDonald Islands", "country_code": "HM"},
    ],
    "Asia": [
        {"name": "Afghanistan", "country_code": "AF"},
        {"name": "Armenia", "country_code": "AM"},
        {"name": "Azerbaijan", "country_code": "AZ"},
        {"name": "Bahrain", "country_code": "BH"},
        {"name": "Bangladesh", "country_code": "BD"},
        {"name": "Bhutan", "country_code": "BT"},
        {"name": "British Indian Ocean Territory", "country_code": "IO"},
        {"name": "Brunei Darussalam", "country_code": "BN"},
        {"name": "Cambodia", "country_code": "KH"},
        {"name": "China", "country_code": "CN"},
        {"name": "Christmas Island", "country_code": "CX"},
        {"name": "Cocos (Keeling) Islands", "country_code": "CC"},
        {"name": "Cyprus", "country_code": "CY"},
        {"name": "Georgia", "country_code": "GE"},
        {"name": "Hong Kong", "country_code": "HK"},
        {"name": "India", "country_code": "IN"},
        {"name": "Indonesia", "country_code": "ID"},
        {"name": "Iran, Islamic Republic of", "country_code": "IR"},
        {"name": "Iraq", "country_code": "IQ"},
        {"name": "Israel", "country_code": "IL"},
        {"name": "Japan", "country_code": "JP"},
        {"name": "Jordan", "country_code": "JO"},
        {"name": "Kazakhstan", "country_code": "KZ"},
        {"name": "Korea, Democratic People's Republic of", "country_code": "KP"},
        {"name": "Korea, Republic of", "country_code": "KR"},
        {"name": "Kuwait", "country_code": "KW"},
        {"name": "Kyrgyzstan", "country_code": "KG"},
        {"name": "Lao People's Democratic Republic", "country_code": "LA"},
        {"name": "Lebanon", "country_code": "LB"},
        {"name": "Macao", "country_code": "MO"},
        {"name": "Malaysia", "country_code": "MY"},
        {"name": "Maldives", "country_code": "MV"},
        {"name": "Mongolia", "country_code": "MN"},
        {"name": "Myanmar", "country_code": "MM"},
        {"name": "Nepal", "country_code": "NP"},
        {"name": "Oman", "country_code": "OM"},
        {"name": "Pakistan", "country_code": "PK"},
        {"name": "Palestine, State of", "country_code": "PS"},
        {"name": "Philippines", "country_code": "PH"},
        {"name": "Qatar", "country_code": "QA"},
        {"name": "Saudi Arabia", "country_code": "SA"},
        {"name": "Singapore", "country_code": "SG"},
        {"name": "Sri Lanka", "country_code": "LK"},
        {"name": "Syrian Arab Republic", "country_code": "SY"},
        {"name": "Taiwan, Province of China", "country_code": "TW"},
        {"name": "Tajikistan", "country_code": "TJ"},
        {"name": "Thailand", "country_code": "TH"},
        {"name": "Timor-Leste", "country_code": "TL"},
        {"name": "Turkey", "country_code": "TR"},
        {"name": "Turkmenistan", "country_code": "TM"},
        {"name": "United Arab Emirates", "country_code": "AE"},
        {"name": "Uzbekistan", "country_code": "UZ"},
        {"name": "Viet Nam", "country_code": "VN"},
        {"name": "Yemen", "country_code": "YE"},
    ],
    "Europe": [
        {"name": "Åland Islands", "country_code": "AX"},
        {"name": "Albania", "country_code": "AL"},
        {"name": "Andorra", "country_code": "AD"},
        {"name": "Austria", "country_code": "AT"},
        {"name": "Belarus", "country_code": "BY"},
        {"name": "Belgium", "country_code": "BE"},
        {"name": "Bosnia and Herzegovina", "country_code": "BA"},
        {"name": "Bulgaria", "country_code": "BG"},
        {"name": "Croatia", "country_code": "HR"},
        {"name": "Czechia", "country_code": "CZ"},
        {"name": "Denmark", "country_code": "DK"},
        {"name": "Estonia", "country_code": "EE"},
        {"name": "Faroe Islands", "country_code": "FO"},
        {"name": "Finland", "country_code": "FI"},
        {"name": "France", "country_code": "FR"},
        {"name": "Germany", "country_code": "DE"},
        {"name": "Gibraltar", "country_code": "GI"},
        {"name": "Greece", "country_code": "GR"},
        {"name": "Guernsey", "country_code": "GG"},
        {"name": "Hungary", "country_code": "HU"},
        {"name": "Iceland", "country_code": "IS"},
        {"name": "Ireland", "country_code": "IE"},
        {"name": "Isle of Man", "country_code": "IM"},
        {"name": "Italy", "country_code": "IT"},
        {"name": "Jersey", "country_code": "JE"},
        {"name": "Kosovo", "country_code": "XK"},
        {"name": "Latvia", "country_code": "LV"},
        {"name": "Liechtenstein", "country_code": "LI"},
        {"name": "Lithuania", "country_code": "LT"},
        {"name": "Luxembourg", "country_code": "LU"},
        {"name": "North Macedonia", "country_code": "MK"},
        {"name": "Malta", "country_code": "MT"},
        {"name": "Moldova, Republic of", "country_code": "MD"},
        {"name": "Monaco", "country_code": "MC"},
        {"name": "Montenegro", "country_code": "ME"},
        {"name": "Netherlands", "country_code": "NL"},
        {"name": "Norway", "country_code": "NO"},
        {"name": "Poland", "country_code": "PL"},
        {"name": "Portugal", "country_code": "PT"},
        {"name": "Romania", "country_code": "RO"},
        {"name": "Russian Federation", "country_code": "RU"},
        {"name": "San Marino", "country_code": "SM"},
        {"name": "Serbia", "country_code": "RS"},
        {"name": "Slovakia", "country_code": "SK"},
        {"name": "Slovenia", "country_code": "SI"},
        {"name": "Spain", "country_code": "ES"},
        {"name": "Svalbard and Jan Mayen", "country_code": "SJ"},
        {"name": "Sweden", "country_code": "SE"},
        {"name": "Switzerland", "country_code": "CH"},
        {"name": "Ukraine", "country_code": "UA"},
        {
            "name": "United Kingdom of Great Britain and Northern Ireland",
            "country_code": "GB",
        },
        {"name": "Vatican City", "country_code": "VA"},
    ],
    "Global South": [
        # source http://www.fc-ssc.org/en/partnership_program/south_south_countries
        {"name": "Afghanistan", "country_code": "AF"},
        {"name": "Algeria", "country_code": "DZ"},
        {"name": "Angola", "country_code": "AO"},
        {"name": "Antigua and Barbuda", "country_code": "AG"},
        {"name": "Argentina", "country_code": "AR"},
        {"name": "Bahamas", "country_code": "BS"},
        {"name": "Bahrain", "country_code": "BH"},
        {"name": "Bangladesh", "country_code": "BD"},
        {"name": "Barbados", "country_code": "BB"},
        {"name": "Belize", "country_code": "BZ"},
        {"name": "Benin", "country_code": "BJ"},
        {"name": "Bhutan", "country_code": "BT"},
        {"name": "Bolivia, Plurinational State of", "country_code": "BO"},
        {"name": "Bosnia and Herzegovina", "country_code": "BA"},
        {"name": "Botswana", "country_code": "BW"},
        {"name": "Brazil", "country_code": "BR"},
        {"name": "Brunei Darussalam", "country_code": "BN"},
        {"name": "Burkina Faso", "country_code": "BF"},
        {"name": "Burundi", "country_code": "BI"},
        {"name": "Cabo Verde", "country_code": "CV"},
        {"name": "Cambodia", "country_code": "KH"},
        {"name": "Cameroon", "country_code": "CM"},
        {"name": "Central African Republic", "country_code": "CF"},
        {"name": "Chad", "country_code": "TD"},
        {"name": "Chile", "country_code": "CL"},
        {"name": "China", "country_code": "CN"},
        {"name": "Colombia", "country_code": "CO"},
        {"name": "Comoros", "country_code": "KM"},
        {"name": "Congo", "country_code": "CG"},
        {"name": "Congo, Democratic Republic of the", "country_code": "CD"},
        {"name": "Costa Rica", "country_code": "CR"},
        {"name": "Cuba", "country_code": "CU"},
        {"name": "Côte d'Ivoire", "country_code": "CI"},
        {"name": "Djibouti", "country_code": "DJ"},
        {"name": "Dominica", "country_code": "DM"},
        {"name": "Dominican Republic", "country_code": "DO"},
        {"name": "Ecuador", "country_code": "EC"},
        {"name": "Egypt", "country_code": "EG"},
        {"name": "El Salvador", "country_code": "SV"},
        {"name": "Equatorial Guinea", "country_code": "GQ"},
        {"name": "Eritrea", "country_code": "ER"},
        {"name": "Eswatini", "country_code": "SZ"},
        {"name": "Ethiopia", "country_code": "ET"},
        {"name": "Fiji", "country_code": "FJ"},
        {"name": "Gabon", "country_code": "GA"},
        {"name": "Gambia", "country_code": "GM"},
        {"name": "Ghana", "country_code": "GH"},
        {"name": "Grenada", "country_code": "GD"},
        {"name": "Guatemala", "country_code": "GT"},
        {"name": "Guinea", "country_code": "GN"},
        {"name": "Guinea-Bissau", "country_code": "GW"},
        {"name": "Guyana", "country_code": "GY"},
        {"name": "Haiti", "country_code": "HT"},
        {"name": "Honduras", "country_code": "HN"},
        {"name": "India", "country_code": "IN"},
        {"name": "Indonesia", "country_code": "ID"},
        {"name": "Iran, Islamic Republic of", "country_code": "IR"},
        {"name": "Iraq", "country_code": "IQ"},
        {"name": "Jamaica", "country_code": "JM"},
        {"name": "Jordan", "country_code": "JO"},
        {"name": "Kenya", "country_code": "KE"},
        {"name": "Kiribati", "country_code": "KI"},
        {"name": "Korea, Democratic People's Republic of", "country_code": "KP"},
        {"name": "Kuwait", "country_code": "KW"},
        {"name": "Lao People's Democratic Republic", "country_code": "LA"},
        {"name": "Lebanon", "country_code": "LB"},
        {"name": "Lesotho", "country_code": "LS"},
        {"name": "Liberia", "country_code": "LR"},
        {"name": "Libya", "country_code": "LY"},
        {"name": "Madagascar", "country_code": "MG"},
        {"name": "Malawi", "country_code": "MW"},
        {"name": "Malaysia", "country_code": "MY"},
        {"name": "Maldives", "country_code": "MV"},
        {"name": "Mali", "country_code": "ML"},
        {"name": "Marshall Islands", "country_code": "MH"},
        {"name": "Mauritania", "country_code": "MR"},
        {"name": "Mauritius", "country_code": "MU"},
        {"name": "Micronesia, Federated States of", "country_code": "FM"},
        {"name": "Mongolia", "country_code": "MN"},
        {"name": "Morocco", "country_code": "MA"},
        {"name": "Mozambique", "country_code": "MZ"},
        {"name": "Myanmar", "country_code": "MM"},
        {"name": "Namibia", "country_code": "NA"},
        {"name": "Nauru", "country_code": "NR"},
        {"name": "Nepal", "country_code": "NP"},
        {"name": "Nicaragua", "country_code": "NI"},
        {"name": "Niger", "country_code": "NE"},
        {"name": "Nigeria", "country_code": "NG"},
        {"name": "Oman", "country_code": "OM"},
        {"name": "Pakistan", "country_code": "PK"},
        {"name": "Palestine, State of", "country_code": "PS"},
        {"name": "Panama", "country_code": "PA"},
        {"name": "Papua New Guinea", "country_code": "PG"},
        {"name": "Paraguay", "country_code": "PY"},
        {"name": "Peru", "country_code": "PE"},
        {"name": "Philippines", "country_code": "PH"},
        {"name": "Qatar", "country_code": "QA"},
        {"name": "Rwanda", "country_code": "RW"},
        {"name": "Saint Kitts and Nevis", "country_code": "KN"},
        {"name": "Saint Lucia", "country_code": "LC"},
        {"name": "Saint Vincent and the Grenadines", "country_code": "VC"},
        {"name": "Samoa", "country_code": "WS"},
        {"name": "Sao Tome and Principe", "country_code": "ST"},
        {"name": "Saudi Arabia", "country_code": "SA"},
        {"name": "Senegal", "country_code": "SN"},
        {"name": "Seychelles", "country_code": "SC"},
        {"name": "Sierra Leone", "country_code": "SL"},
        {"name": "Singapore", "country_code": "SG"},
        {"name": "Solomon Islands", "country_code": "SB"},
        {"name": "Somalia", "country_code": "SO"},
        {"name": "South Africa", "country_code": "ZA"},
        {"name": "South Sudan", "country_code": "SS"},
        {"name": "Sri Lanka", "country_code": "LK"},
        {"name": "Sudan", "country_code": "SD"},
        {"name": "Suriname", "country_code": "SR"},
        {"name": "Syrian Arab Republic", "country_code": "SY"},
        {"name": "Tajikistan", "country_code": "TJ"},
        {"name": "Tanzania, United Republic of", "country_code": "TZ"},
        {"name": "Thailand", "country_code": "TH"},
        {"name": "Timor-Leste", "country_code": "TL"},
        {"name": "Togo", "country_code": "TG"},
        {"name": "Tonga", "country_code": "TO"},
        {"name": "Trinidad and Tobago", "country_code": "TT"},
        {"name": "Tunisia", "country_code": "TN"},
        {"name": "Turkmenistan", "country_code": "TM"},
        {"name": "Uganda", "country_code": "UG"},
        {"name": "United Arab Emirates", "country_code": "AE"},
        {"name": "Uruguay", "country_code": "UY"},
        {"name": "Vanuatu", "country_code": "VU"},
        {"name": "Venezuela, Bolivarian Republic of", "country_code": "VE"},
        {"name": "Viet Nam", "country_code": "VN"},
        {"name": "Yemen", "country_code": "YE"},
        {"name": "Zambia", "country_code": "ZM"},
        {"name": "Zimbabwe", "country_code": "ZW"},
    ],
    "North America": [
        {"name": "Anguilla", "country_code": "AI"},
        {"name": "Antigua and Barbuda", "country_code": "AG"},
        {"name": "Aruba", "country_code": "AW"},
        {"name": "Bahamas", "country_code": "BS"},
        {"name": "Barbados", "country_code": "BB"},
        {"name": "Belize", "country_code": "BZ"},
        {"name": "Bermuda", "country_code": "BM"},
        {"name": "Bonaire, Sint Eustatius and Saba", "country_code": "BQ"},
        {"name": "Canada", "country_code": "CA"},
        {"name": "Cayman Islands", "country_code": "KY"},
        {"name": "Costa Rica", "country_code": "CR"},
        {"name": "Cuba", "country_code": "CU"},
        {"name": "Curaçao", "country_code": "CW"},
        {"name": "Dominica", "country_code": "DM"},
        {"name": "Dominican Republic", "country_code": "DO"},
        {"name": "El Salvador", "country_code": "SV"},
        {"name": "Greenland", "country_code": "GL"},
        {"name": "Grenada", "country_code": "GD"},
        {"name": "Guadeloupe", "country_code": "GP"},
        {"name": "Guatemala", "country_code": "GT"},
        {"name": "Haiti", "country_code": "HT"},
        {"name": "Honduras", "country_code": "HN"},
        {"name": "Jamaica", "country_code": "JM"},
        {"name": "Martinique", "country_code": "MQ"},
        {"name": "Mexico", "country_code": "MX"},
        {"name": "Montserrat", "country_code": "MS"},
        {"name": "Nicaragua", "country_code": "NI"},
        {"name": "Panama", "country_code": "PA"},
        {"name": "Puerto Rico", "country_code": "PR"},
        {"name": "Saint Barthélemy", "country_code": "BL"},
        {"name": "Saint Kitts and Nevis", "country_code": "KN"},
        {"name": "Saint Lucia", "country_code": "LC"},
        {"name": "Saint Martin (French part)", "country_code": "MF"},
        {"name": "Sint Maarten", "country_code": "SX"},
        {"name": "Saint Pierre and Miquelon", "country_code": "PM"},
        {"name": "Saint Vincent and the Grenadines", "country_code": "VC"},
        {"name": "Trinidad and Tobago", "country_code": "TT"},
        {"name": "Turks and Caicos Islands", "country_code": "TC"},
        {"name": "United States of America", "country_code": "US"},
        {"name": "Virgin Islands, British", "country_code": "VG"},
        {"name": "Virgin Islands, U.S.", "country_code": "VI"},
    ],
    "Oceania": [
        {"name": "American Samoa", "country_code": "AS"},
        {"name": "Australia", "country_code": "AU"},
        {"name": "Cook Islands", "country_code": "CK"},
        {"name": "Fiji", "country_code": "FJ"},
        {"name": "French Polynesia", "country_code": "PF"},
        {"name": "Guam", "country_code": "GU"},
        {"name": "Kiribati", "country_code": "KI"},
        {"name": "Marshall Islands", "country_code": "MH"},
        {"name": "Micronesia, Federated States of", "country_code": "FM"},
        {"name": "Nauru", "country_code": "NR"},
        {"name": "New Caledonia", "country_code": "NC"},
        {"name": "New Zealand", "country_code": "NZ"},
        {"name": "Niue", "country_code": "NU"},
        {"name": "Norfolk Island", "country_code": "NF"},
        {"name": "Northern Mariana Islands", "country_code": "MP"},
        {"name": "Palau", "country_code": "PW"},
        {"name": "Papua New Guinea", "country_code": "PG"},
        {"name": "Pitcairn", "country_code": "PN"},
        {"name": "Samoa", "country_code": "WS"},
        {"name": "Solomon Islands", "country_code": "SB"},
        {"name": "Tokelau", "country_code": "TK"},
        {"name": "Tonga", "country_code": "TO"},
        {"name": "Tuvalu", "country_code": "TV"},
        {"name": "Vanuatu", "country_code": "VU"},
        {"name": "Wallis and Futuna", "country_code": "WF"},
    ],
    "South America": [
        {"name": "Argentina", "country_code": "AR"},
        {"name": "Bolivia, Plurinational State of", "country_code": "BO"},
        {"name": "Brazil", "country_code": "BR"},
        {"name": "Chile", "country_code": "CL"},
        {"name": "Colombia", "country_code": "CO"},
        {"name": "Ecuador", "country_code": "EC"},
        {"name": "Falkland Islands (Malvinas)", "country_code": "FK"},
        {"name": "French Guiana", "country_code": "GF"},
        {"name": "Guyana", "country_code": "GY"},
        {"name": "Paraguay", "country_code": "PY"},
        {"name": "Peru", "country_code": "PE"},
        {"name": "South Georgia and the South Sandwich Islands", "country_code": "GS"},
        {"name": "Suriname", "country_code": "SR"},
        {"name": "Uruguay", "country_code": "UY"},
        {"name": "Venezuela, Bolivarian Republic of", "country_code": "VE"},
    ],
}
