import os

CACHE_TYPE = "RedisCache"
CACHE_DEFAULT_TIMEOUT = 300
CACHE_REDIS_URL = os.environ.get("REDISCLOUD_URL")
ENV = os.environ.get("FLASK_ENV", "production")
ES_URL = os.environ.get("ES_URL_PROD", "http://elastic:testpass@127.0.0.1:9200")
DEBUG = ENV == "development"
JSON_SORT_KEYS = False
SECRET_KEY = os.environ.get("SECRET_KEY")

# indexes
AUTHORS_INDEX = "authors-v8"
CONCEPTS_INDEX = "concepts-v7"
INSTITUTIONS_INDEX = "institutions-v4"
VENUES_INDEX = "venues-v5"
WORKS_INDEX = "works-v15-*,-*invalid-data"

DO_NOT_GROUP_BY = [
    "cited_by",
    "display_name",
    "doi",
    "ids.mag",
    "ids.pmid",
    "ids.pmcid",
    "mag",
    "pmid",
    "pmcid",
    "related_to",
]

EXTERNAL_ID_FIELDS = [
    "has_doi",
    "has_issn",
    "has_orcid",
    "has_ror",
    "has_wikidata",
]

BOOLEAN_TEXT_FIELDS = ["has_abstract", "has_ngrams", "has_references"]

TRANSFORMS = [
    {
        "field": "x_concepts.id",
        "index_name": "authors-transform-x-concepts-id",
        "parent_index": "authors",
    }
]

# source http://www.fc-ssc.org/en/partnership_program/south_south_countries
GLOBAL_SOUTH_COUNTRIES = [
    {"name": "Afghanistan", "country_code": "AF"},
    {"name": "Algeria", "country_code": "DZ"},
    {"name": "Angola", "country_code": "AO"},
    {"name": "Antigua and Barbuda", "country_code": "AG"},
    {"name": "Argentina", "country_code": "AR"},
    {"name": "Bahamas", "country_code": "BS"},
    {"name": "Bahrain", "country_code": "BH"},
    {"name": "Bangladesh", "country_code": "BD"},
    {"name": "Barbados", "country_code": "BB"},
    {"name": "Belize", "country_code": "BZ"},
    {"name": "Benin", "country_code": "BJ"},
    {"name": "Bhutan", "country_code": "BT"},
    {"name": "Bolivia, Plurinational State of", "country_code": "BO"},
    {"name": "Bosnia and Herzegovina", "country_code": "BA"},
    {"name": "Botswana", "country_code": "BW"},
    {"name": "Brazil", "country_code": "BR"},
    {"name": "Brunei Darussalam", "country_code": "BN"},
    {"name": "Burkina Faso", "country_code": "BF"},
    {"name": "Burundi", "country_code": "BI"},
    {"name": "Cabo Verde", "country_code": "CV"},
    {"name": "Cambodia", "country_code": "KH"},
    {"name": "Cameroon", "country_code": "CM"},
    {"name": "Central African Republic", "country_code": "CF"},
    {"name": "Chad", "country_code": "TD"},
    {"name": "Chile", "country_code": "CL"},
    {"name": "China", "country_code": "CN"},
    {"name": "Colombia", "country_code": "CO"},
    {"name": "Comoros", "country_code": "KM"},
    {"name": "Congo", "country_code": "CG"},
    {"name": "Congo, Democratic Republic of the", "country_code": "CD"},
    {"name": "Costa Rica", "country_code": "CR"},
    {"name": "Cuba", "country_code": "CU"},
    {"name": "Côte d'Ivoire", "country_code": "CI"},
    {"name": "Djibouti", "country_code": "DJ"},
    {"name": "Dominica", "country_code": "DM"},
    {"name": "Dominican Republic", "country_code": "DO"},
    {"name": "Ecuador", "country_code": "EC"},
    {"name": "Egypt", "country_code": "EG"},
    {"name": "El Salvador", "country_code": "SV"},
    {"name": "Equatorial Guinea", "country_code": "GQ"},
    {"name": "Eritrea", "country_code": "ER"},
    {"name": "Eswatini", "country_code": "SZ"},
    {"name": "Ethiopia", "country_code": "ET"},
    {"name": "Fiji", "country_code": "FJ"},
    {"name": "Gabon", "country_code": "GA"},
    {"name": "Gambia", "country_code": "GM"},
    {"name": "Ghana", "country_code": "GH"},
    {"name": "Grenada", "country_code": "GD"},
    {"name": "Guatemala", "country_code": "GT"},
    {"name": "Guinea", "country_code": "GN"},
    {"name": "Guinea-Bissau", "country_code": "GW"},
    {"name": "Guyana", "country_code": "GY"},
    {"name": "Haiti", "country_code": "HT"},
    {"name": "Honduras", "country_code": "HN"},
    {"name": "India", "country_code": "IN"},
    {"name": "Indonesia", "country_code": "ID"},
    {"name": "Iran, Islamic Republic of", "country_code": "IR"},
    {"name": "Iraq", "country_code": "IQ"},
    {"name": "Jamaica", "country_code": "JM"},
    {"name": "Jordan", "country_code": "JO"},
    {"name": "Kenya", "country_code": "KE"},
    {"name": "Kiribati", "country_code": "KI"},
    {"name": "Korea, Democratic People's Republic of", "country_code": "KP"},
    {"name": "Kuwait", "country_code": "KW"},
    {"name": "Lao People's Democratic Republic", "country_code": "LA"},
    {"name": "Lebanon", "country_code": "LB"},
    {"name": "Lesotho", "country_code": "LS"},
    {"name": "Liberia", "country_code": "LR"},
    {"name": "Libya", "country_code": "LY"},
    {"name": "Madagascar", "country_code": "MG"},
    {"name": "Malawi", "country_code": "MW"},
    {"name": "Malaysia", "country_code": "MY"},
    {"name": "Maldives", "country_code": "MV"},
    {"name": "Mali", "country_code": "ML"},
    {"name": "Marshall Islands", "country_code": "MH"},
    {"name": "Mauritania", "country_code": "MR"},
    {"name": "Mauritius", "country_code": "MU"},
    {"name": "Micronesia, Federated States of", "country_code": "FM"},
    {"name": "Mongolia", "country_code": "MN"},
    {"name": "Morocco", "country_code": "MA"},
    {"name": "Mozambique", "country_code": "MZ"},
    {"name": "Myanmar", "country_code": "MM"},
    {"name": "Namibia", "country_code": "NA"},
    {"name": "Nauru", "country_code": "NR"},
    {"name": "Nepal", "country_code": "NP"},
    {"name": "Nicaragua", "country_code": "NI"},
    {"name": "Niger", "country_code": "NE"},
    {"name": "Nigeria", "country_code": "NG"},
    {"name": "Oman", "country_code": "OM"},
    {"name": "Pakistan", "country_code": "PK"},
    {"name": "Palestine, State of", "country_code": "PS"},
    {"name": "Panama", "country_code": "PA"},
    {"name": "Papua New Guinea", "country_code": "PG"},
    {"name": "Paraguay", "country_code": "PY"},
    {"name": "Peru", "country_code": "PE"},
    {"name": "Philippines", "country_code": "PH"},
    {"name": "Qatar", "country_code": "QA"},
    {"name": "Rwanda", "country_code": "RW"},
    {"name": "Saint Kitts and Nevis", "country_code": "KN"},
    {"name": "Saint Lucia", "country_code": "LC"},
    {"name": "Saint Vincent and the Grenadines", "country_code": "VC"},
    {"name": "Samoa", "country_code": "WS"},
    {"name": "Sao Tome and Principe", "country_code": "ST"},
    {"name": "Saudi Arabia", "country_code": "SA"},
    {"name": "Senegal", "country_code": "SN"},
    {"name": "Seychelles", "country_code": "SC"},
    {"name": "Sierra Leone", "country_code": "SL"},
    {"name": "Singapore", "country_code": "SG"},
    {"name": "Solomon Islands", "country_code": "SB"},
    {"name": "Somalia", "country_code": "SO"},
    {"name": "South Africa", "country_code": "ZA"},
    {"name": "South Sudan", "country_code": "SS"},
    {"name": "Sri Lanka", "country_code": "LK"},
    {"name": "Sudan", "country_code": "SD"},
    {"name": "Suriname", "country_code": "SR"},
    {"name": "Syrian Arab Republic", "country_code": "SY"},
    {"name": "Tajikistan", "country_code": "TJ"},
    {"name": "Tanzania, United Republic of", "country_code": "TZ"},
    {"name": "Thailand", "country_code": "TH"},
    {"name": "Timor-Leste", "country_code": "TL"},
    {"name": "Togo", "country_code": "TG"},
    {"name": "Tonga", "country_code": "TO"},
    {"name": "Trinidad and Tobago", "country_code": "TT"},
    {"name": "Tunisia", "country_code": "TN"},
    {"name": "Turkmenistan", "country_code": "TM"},
    {"name": "Uganda", "country_code": "UG"},
    {"name": "United Arab Emirates", "country_code": "AE"},
    {"name": "Uruguay", "country_code": "UY"},
    {"name": "Vanuatu", "country_code": "VU"},
    {"name": "Venezuela, Bolivarian Republic of", "country_code": "VE"},
    {"name": "Viet Nam", "country_code": "VN"},
    {"name": "Yemen", "country_code": "YE"},
    {"name": "Zambia", "country_code": "ZM"},
    {"name": "Zimbabwe", "country_code": "ZW"},
]
