"""
OQL v1.1 -> v2 gap report  (oxjob #330, feeds roadmap step 3).

Runs the *current production* translator (query_translation/oql_parser.py +
oql_renderer.py — the v1.1 surface) against the v2 normative corpus and reports
which rows it fails and why. This is a hand-off artifact, NOT a pass/fail gate:
the v1.1 impl is the OLD surface by design, so failures are expected — the value
is a complete, categorized list of what roadmap step 3 (reconcile the parser/
renderer to v2, gated on #323) has to close.

Categories per row:
  PASS            v1.1 parse(oql) canonicalizes equal to the v2 oqo
  MISSING-FEATURE v1.1 raised / couldn't parse the v2 surface at all
  SPEC-MISMATCH   v1.1 parsed but produced a different (v1.1-semantics) OQO
  ENGINE-BUG      representable in spec, but the live ES engine mishandles it
                  (annotated from evidence/engine_findings.md, not executed here)

Usage:
  .venv-oql/bin/python tests/oql/gap_report.py [--out docs/oql/gap_report.md]
"""
import argparse
import os
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import tests.oql._qt_loader  # noqa: F401
from query_translation.oqo import OQO  # noqa: E402
from query_translation.oqo_canonicalizer import canonicalize_oqo  # noqa: E402
from query_translation.oql_parser import parse_oql_to_oqo  # noqa: E402
from query_translation.oql_renderer import render_oqo_to_oql  # noqa: E402
from tests.oql.oql_v2 import parse as v2_parse  # noqa: E402

_NOOP_RESOLVER = lambda _id: None  # keep the v1.1 renderer offline (no network)

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CORPUS = os.path.join(ROOT, "docs", "oql", "corpus.yaml")

# Rows the spec marks ✓ but the LIVE engine mishandles (see engine_findings.md).
ENGINE_BUGS = {
    "L02b": "trailing wildcard `phone*` 500s on the live server (not yet shipped)",
}


def _canon(oqo: OQO) -> dict:
    return canonicalize_oqo(oqo).to_dict()


def classify(row):
    oql = row.get("oql")
    if row["status"] == "boundary" or not oql:
        return ("BOUNDARY", "non-representable; documented boundary")
    if row["status"] == "error":
        # v1.1 has no v2 diagnostics; report whether it (wrongly) accepts the input.
        try:
            parse_oql_to_oqo(oql)
            return ("SPEC-MISMATCH", "v1.1 silently accepts an input v2 rejects (no diagnostic)")
        except Exception:
            return ("PASS", "v1.1 also rejects (no v2 diagnostic code though)")
    # ok / hint rows
    try:
        got = parse_oql_to_oqo(oql)
    except Exception as e:
        msg = f"{type(e).__name__}: {str(e)[:120]}"
        return ("MISSING-FEATURE", msg)
    if "oqo" not in row:
        return ("UNKNOWN", "no oracle to compare (round-trip-only row)")
    try:
        if _canon(got) == _canon(OQO.from_dict(row["oqo"])):
            cat = "PASS"
            detail = "v1.1 parse matches the v2 oqo"
            if row["id"] in ENGINE_BUGS:
                cat, detail = "ENGINE-BUG", ENGINE_BUGS[row["id"]]
            return (cat, detail)
    except Exception as e:
        return ("SPEC-MISMATCH", f"compare error: {e}")
    return ("SPEC-MISMATCH", "v1.1 parses but to a different OQO than v2")


def classify_render(row):
    """v1.1 renderer (OQO -> OQL) direction: does it produce v2-parseable OQL that
    means the same OQO? Categories: RENDER-OK / RENDER-MISSING / RENDER-MISMATCH."""
    if row["status"] != "ok" or "oqo" not in row:
        return None
    oqo = OQO.from_dict(row["oqo"])
    try:
        oql = render_oqo_to_oql(oqo, entity_resolver=_NOOP_RESOLVER)
    except Exception as e:
        return ("RENDER-MISSING", f"{type(e).__name__}: {str(e)[:80]}")
    try:
        if _canon(v2_parse(oql)) == _canon(oqo):
            return ("RENDER-OK", "v1.1 render is v2-parseable & equal")
    except Exception as e:
        return ("RENDER-MISMATCH", f"v1.1 output not v2-parseable: {str(e)[:80]}")
    return ("RENDER-MISMATCH", "v1.1 render parses to a different OQO")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "oql", "gap_report.md"))
    args = ap.parse_args()

    rows = yaml.safe_load(open(CORPUS))["rows"]
    results = [(r, *classify(r)) for r in rows]

    from collections import Counter
    counts = Counter(cat for _, cat, _ in results)
    order = ["PASS", "MISSING-FEATURE", "SPEC-MISMATCH", "ENGINE-BUG", "BOUNDARY", "UNKNOWN"]

    lines = []
    lines.append("# OQL v1.1 → v2 gap report")
    lines.append("")
    lines.append("> Generated by `tests/oql/gap_report.py` against `docs/oql/corpus.yaml`.")
    lines.append("> The current production translator is the **v1.1** surface; failures here")
    lines.append("> are the work-list for roadmap step 3 (reconcile parser/renderer to v2,")
    lines.append("> gated on #323). This is an artifact, not a pass/fail gate.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Category | Count | Meaning |")
    lines.append("|---|---|---|")
    meaning = {
        "PASS": "v1.1 already produces the v2 OQO",
        "MISSING-FEATURE": "v1.1 can't parse the v2 surface (raises)",
        "SPEC-MISMATCH": "v1.1 parses but to different (v1.1) semantics, or wrongly accepts an error case",
        "ENGINE-BUG": "spec-valid, but the live ES engine mishandles it",
        "BOUNDARY": "documented non-representable",
        "UNKNOWN": "no oracle (round-trip-only row)",
    }
    for cat in order:
        if counts.get(cat):
            lines.append(f"| {cat} | {counts[cat]} | {meaning[cat]} |")
    lines.append(f"| **Total** | **{len(results)}** | |")
    lines.append("")

    for cat in order:
        bucket = [(r, d) for r, c, d in results if c == cat]
        if not bucket:
            continue
        lines.append(f"## {cat} ({len(bucket)})")
        lines.append("")
        lines.append("| Row | Detail | OQL |")
        lines.append("|---|---|---|")
        for r, d in bucket:
            oql = (r.get("oql") or "—").replace("|", "\\|")
            if len(oql) > 90:
                oql = oql[:87] + "…"
            lines.append(f"| {r['id']} | {d} | `{oql}` |")
        lines.append("")

    # --- renderer direction (OQO -> OQL) ---
    rend = [(r, *res) for r in rows if (res := classify_render(r))]
    rcounts = Counter(c for _, c, _ in rend)
    lines.append("## Renderer direction — v1.1 `oql_renderer` (OQO → OQL)")
    lines.append("")
    lines.append("Does the v1.1 renderer emit v2-parseable OQL that round-trips to the same OQO?")
    lines.append("")
    lines.append("| Category | Count |")
    lines.append("|---|---|")
    for cat in ("RENDER-OK", "RENDER-MISSING", "RENDER-MISMATCH"):
        if rcounts.get(cat):
            lines.append(f"| {cat} | {rcounts[cat]} |")
    lines.append("")
    bad = [(r, d) for r, c, d in rend if c != "RENDER-OK"]
    if bad:
        lines.append("Rows the v1.1 renderer does not yet emit in v2 form:")
        lines.append("")
        lines.append("| Row | Detail |")
        lines.append("|---|---|")
        for r, d in bad:
            lines.append(f"| {r['id']} | {d} |")
        lines.append("")

    out = "\n".join(lines) + "\n"
    with open(args.out, "w") as fh:
        fh.write(out)
    print(f"wrote {args.out}")
    print("  " + "  ".join(f"{c}={counts.get(c,0)}" for c in order if counts.get(c)))


if __name__ == "__main__":
    main()
