# shared alternate_names, used for search among filters
ALTERNATE_NAMES = {
    "is_global_south": ["asia", "africa", "india", "south", "america", "southeast", "latin"],
    "openalex": ["id"],
    "concept": ["topic", "keyword"],
    "is_oa": ["open", "access"],
    "source.is_oa": ["open", "access", "full", "text", "pdf", "free", "download"],
    "source.is_in_doaj": ["directory", "open", "access", "journal"],
    "is_accepted": ["accepted", "peer", "review"],
    "is_published": ["publish", "peer", "review"],
    "has_doi": ["identifier", "crossref", "doi"],
    "has_fulltext": ["full", "text", "search", "ngrams", "pdf"],
    "has_pmid": ["pubmed"],
    "has_pmcid": ["pubmed", "central"],
    "has_references": ["outgoing", "citations"],
    "is_paratext": ["paratext", "cover", "table", "contents", "issue", "volume"],
    "source.issn": ["issn", "journal"],
    "source.type": ["source", "type", "journal", "repository"],
    "sustainable_development_goals": ["un", "sdg"],
    "work.type": [
        "article",
        "book",
        "editorial",
        "paratext",
        "monograph",
        "letter",
        "editorial",
    ],
    "any_repository_has_fulltext": [
        "full",
        "text",
        "free",
        "pdf",
        "open",
        "access",
        "download",
    ],
    "publication_date": ["date", "year", "time"],
    "author": ["contributor", "writer", "authorship", "person", "people", "name"],
    "institution": ["institution", "university", "affiliation"],
    "corresponding_institutions": ["institution", "university", "affiliation"],
    "source": ["journal", "conference", "repository", "book", "issn", "arxiv"],
    "publisher": ["company", "springer", "elsevier", "wiley", "press"],
    "repository": ["arxiv", "hal"],
    "license": [
        "licence",
        "open",
        "access",
        "attribution",
        "creative",
        "commons",
        "cc",
    ],
    "language": [
        "english",
        "german",
        "french",
        "spanish",
        "japanese",
        "chinese",
        "korean",
    ],
    "cited_by": ["references", "outgoing", "citations"],
    "cites": ["incoming", "citations"],
    "apc": ["article", "processing", "charge", "payment", "price"],
    "country": ["geo", "international", "global"],
    "continent": ["asia", "america", "africa", "australia", "oceania", "europe"],
    "institution.type": ["university", "healthcare", "education", "industry", "company"],
}
