from core.fields import (BooleanField, DateField, OpenAlexIDField, PhraseField,
                         RangeField, SearchField, TermField)

fields = [
    BooleanField(
        param="is_oa", alias="open_access.is_oa", custom_es_field="open_access__is_oa"
    ),
    BooleanField(param="is_paratext"),
    BooleanField(param="is_retracted"),
    BooleanField(param="open_access.is_oa"),
    DateField(
        param="from_publication_date",
        custom_es_field="publication_date",
    ),
    DateField(param="publication_date"),
    DateField(
        param="to_publication_date",
        custom_es_field="publication_date",
    ),
    OpenAlexIDField(param="alternate_host_venues.id"),
    OpenAlexIDField(
        param="author.id",
        alias="authorships.author.id",
        custom_es_field="authorships__author__id__lower",
    ),
    OpenAlexIDField(param="authorships.author.id"),
    OpenAlexIDField(param="authorships.institutions.id"),
    OpenAlexIDField(
        param="cites",
        alias="referenced_works",
        custom_es_field="referenced_works__lower",
    ),
    OpenAlexIDField(
        param="concept.id", alias="concepts.id", custom_es_field="concepts__id__lower"
    ),
    OpenAlexIDField(param="concepts.id"),
    OpenAlexIDField(param="host_venue.id"),
    OpenAlexIDField(
        param="institution.id",
        alias="authorships.institutions.id",
        custom_es_field="authorships__institutions__id__lower",
    ),
    OpenAlexIDField(
        param="institutions.id",
        alias="authorships.institutions.id",
        custom_es_field="authorships__institutions__id__lower",
    ),
    OpenAlexIDField(
        param="journal.id",
        alias="host_venue.id",
        custom_es_field="host_venue__id__lower",
    ),
    OpenAlexIDField(param="referenced_works"),
    PhraseField(param="host_venue.publisher"),
    RangeField(param="cited_by_count"),
    RangeField(param="publication_year"),
    SearchField(param="display_name.search"),
    SearchField(param="title.search"),
    TermField(param="alternate_host_venues.license"),
    TermField(param="alternate_host_venues.version"),
    TermField(
        param="author.orcid",
        alias="authorships.author.orcid",
        custom_es_field="authorships__author__orcid__lower",
    ),
    TermField(param="authorships.author.orcid"),
    TermField(param="authorships.institutions.country_code"),
    TermField(param="authorships.institutions.ror"),
    TermField(param="authorships.institutions.type"),
    TermField(param="concepts.wikidata"),
    TermField(param="display_name"),
    TermField(param="host_venue.issn"),
    TermField(
        param="institutions.country_code",
        alias="authors.institutions.country_code",
        custom_es_field="authorships__institutions__country_code__lower",
    ),
    TermField(
        param="institutions.ror",
        alias="authorships.institutions.ror",
        custom_es_field="authorships__institutions__ror__lower",
    ),
    TermField(
        param="institutions.type",
        alias="authorships.institutions.type",
        custom_es_field="authorships__institutions__type__lower",
    ),
    TermField(
        param="oa_status",
        alias="open_access.oa_status",
        custom_es_field="open_access__oa_status__lower",
    ),
    TermField(param="open_access.oa_status"),
    TermField(param="type"),
]

fields_dict = {f.param: f for f in fields}
