from core.fields import (
    BooleanField,
    DateField,
    DateTimeField,
    OpenAlexIDField,
    PhraseField,
    RangeField,
    SearchField,
    TermField,
)

fields = [
    BooleanField(
        param=f"authorships.institutions.is_global_south",
        custom_es_field="authorships.institutions.country_code",
    ),
    BooleanField(param="authorships.is_corresponding"),
    BooleanField(param="best_oa_location.is_oa"),
    BooleanField(param="best_oa_location.source.is_oa"),
    BooleanField(param="best_oa_location.source.is_in_doaj"),
    BooleanField(
        param="best_oa_location.is_accepted",
        docstring="The work has an Open Access version that has been accepted for publication",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object/location-object#is_accepted",
    ),
    BooleanField(
        param="best_oa_location.is_published",
        docstring="The work has an Open Access version that has been published",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object/location-object#is_published",
    ),
    BooleanField(
        param="has_abstract",
        custom_es_field="abstract",
        docstring="Abstract is available for the work",
        documentation_link="https://docs.openalex.org/api-entities/works/filter-works#has_abstract",
    ),
    BooleanField(
        param="has_doi",
        custom_es_field="ids.doi",
        docstring="The work has a DOI (Digital Object Identifier). Usually, this means that a work has been indexed by Crossref.",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#doi",
    ),
    BooleanField(param="has_fulltext"),
    BooleanField(
        param="has_orcid",
        custom_es_field="authorships.author.orcid",
        docstring="The work has at least one author with an ORCID",
        documentation_link="https://docs.openalex.org/api-entities/authors/author-object#orcid",
    ),
    BooleanField(
        param="has_pmid",
        custom_es_field="ids.pmid",
        docstring="The work is in PubMed",
        documentation_link="https://docs.openalex.org/api-entities/works/filter-works#has_pmid",
    ),
    BooleanField(
        param="has_pmcid",
        custom_es_field="ids.pmcid",
        docstring="The work is in PubMed Central",
        documentation_link="https://docs.openalex.org/api-entities/works/filter-works#has_pmcid",
    ),
    BooleanField(param="has_references", custom_es_field="referenced_works"),
    BooleanField(
        param="has_ngrams",
        custom_es_field="fulltext",
        docstring="The work has full text available to search",
        documentation_link="https://docs.openalex.org/api-entities/works/filter-works#has_ngrams",
    ),
    BooleanField(param="has_oa_accepted_or_published_version"),
    BooleanField(param="has_oa_submitted_version"),
    BooleanField(
        param="has_old_authors",
        custom_es_field="authorships.uthor.id",
    ),
    BooleanField(param="has_pdf_url", custom_es_field="locations.pdf_url"),
    BooleanField(
        param="has_raw_affiliation_string",
        custom_es_field="authorships.raw_affiliation_strings",
    ),
    BooleanField(
        param="institutions.is_global_south",
        custom_es_field="authorships.institutions.country_code",
        docstring="The work has affiliated institutions located in the Global South. The Global South is a term used to identify regions within Latin America, Asia, Africa, and Oceania.",
        documentation_link="https://docs.openalex.org/api-entities/geo/regions",
    ),
    BooleanField(
        param="is_corresponding", custom_es_field="authorships.is_corresponding"
    ),
    BooleanField(param="is_oa", alias="open_access.is_oa"),
    BooleanField(
        param="is_paratext",
        docstring='We have marked the work as "paratext". Paratext means things like front/back cover, table of contents, and issue information.',
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#is_paratext",
    ),
    BooleanField(
        param="is_retracted",
        docstring="The work has been retracted",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#is_retracted",
    ),
    BooleanField(param="locations.is_oa"),
    BooleanField(param="locations.source.is_oa"),
    BooleanField(
        param="locations.source.has_issn", custom_es_field="locations.source.issn"
    ),
    BooleanField(param="locations.source.is_in_doaj"),
    BooleanField(param="locations.is_accepted"),
    BooleanField(param="locations.is_published"),
    BooleanField(
        param="open_access.is_oa",
        docstring="The work is Open Access, meaning that you can read the full text without needing to pay money or log in",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#is_oa-1",
    ),
    BooleanField(
        param="open_access.any_repository_has_fulltext",
        docstring="The work’s full text is free in an Open Access repository",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#any_repository_has_fulltext",
    ),
    BooleanField(param="primary_location.is_oa"),
    BooleanField(
        param="primary_location.source.is_oa",
        docstring="The work is in a source that is Open Access. This is different than whether the work itself is Open Access, because the OA status of a source can change",
        documentation_link="https://docs.openalex.org/api-entities/sources/source-object#is_oa",
    ),
    BooleanField(
        param="primary_location.source.is_in_doaj",
        docstring="The work is published in a journal that is in DOAJ, the Directory of Open Access Journals",
        documentation_link="https://docs.openalex.org/api-entities/sources/source-object#is_in_doaj",
    ),
    BooleanField(param="primary_location.is_accepted"),
    BooleanField(param="primary_location.is_published"),
    BooleanField(
        param="primary_location.source.has_issn",
        custom_es_field="primary_location.source.issn",
    ),
    DateField(
        param="from_created_date",
        custom_es_field="created_date",
    ),
    DateField(
        param="from_publication_date",
        custom_es_field="publication_date",
    ),
    DateTimeField(
        param="from_updated_date",
        custom_es_field="updated_date",
    ),
    DateTimeField(
        param="to_updated_date",
        custom_es_field="updated_date",
    ),
    DateField(param="publication_date"),
    DateField(
        param="to_publication_date",
        custom_es_field="publication_date",
    ),
    OpenAlexIDField(param="author.id", alias="authorships.author.id"),
    OpenAlexIDField(
        param="authorships.author.id",
        docstring="The authors of a work",
        documentation_link="https://docs.openalex.org/api-entities/authors",
    ),
    OpenAlexIDField(
        param="authorships.institutions.id",
        docstring="The institutional affiliations claimed by the authors of a work",
        documentation_link="https://docs.openalex.org/api-entities/institutions",
    ),
    OpenAlexIDField(
        param="authorships.institutions.lineage",
        custom_es_field="authorships.institutions.lineage",
    ),
    OpenAlexIDField(
        param="corresponding_author_ids",
        docstring="The work's corresponding author(s)",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object/authorship-object#is_corresponding",
    ),
    OpenAlexIDField(
        param="corresponding_institution_ids",
        docstring="The institutions to which the corresponding author(s) of a work claim affiliation",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#corresponding_institution_ids",
    ),
    OpenAlexIDField(param="best_oa_location.source.id"),
    OpenAlexIDField(param="best_oa_location.source.host_organization"),
    OpenAlexIDField(param="best_oa_location.source.host_organization_lineage"),
    OpenAlexIDField(
        param="cited_by",
        docstring="The work's outgoing citations, or references",
        documentation_link="https://docs.openalex.org/api-entities/works/filter-works#cited_by",
    ),
    OpenAlexIDField(
        param="cites",
        alias="referenced_works",
        docstring="The work's incoming citations",
        documentation_link="https://docs.openalex.org/api-entities/works/filter-works#cites",
    ),
    OpenAlexIDField(param="concept.id", alias="concepts.id"),
    OpenAlexIDField(
        param="concepts.id",
        docstring="Concepts are abstract ideas that the work is about",
        documentation_link="https://docs.openalex.org/api-entities/concepts",
    ),
    OpenAlexIDField(
        param="grants.funder",
        custom_es_field="grants.funder.keyword",
        docstring="The funders listed in the work's grants",
        documentation_link="https://docs.openalex.org/api-entities/funders",
    ),
    OpenAlexIDField(param="host_venue.id"),
    OpenAlexIDField(
        param="ids.openalex",
        docstring="The OpenAlex ID for a work",
        documentation_link="https://docs.openalex.org/how-to-use-the-api/get-single-entities#the-openalex-id",
    ),
    OpenAlexIDField(param="institution.id", alias="authorships.institutions.id"),
    OpenAlexIDField(param="institutions.id", alias="authorships.institutions.id"),
    OpenAlexIDField(param="journal", custom_es_field="primary_location.source.id"),
    OpenAlexIDField(param="locations.source.id"),
    OpenAlexIDField(
        param="locations.source.host_institution_lineage",
        custom_es_field="locations.source.host_organization_lineage",
    ),
    OpenAlexIDField(param="locations.source.host_organization"),
    OpenAlexIDField(param="locations.source.host_organization_lineage"),
    OpenAlexIDField(
        param="locations.source.publisher_lineage",
        custom_es_field="locations.source.host_organization_lineage",
    ),
    OpenAlexIDField(
        param="primary_location.source.host_institution_lineage",
        custom_es_field="primary_location.source.host_organization_lineage",
    ),
    OpenAlexIDField(
        param="primary_location.source.id",
        docstring="The primary source the work is in, such as journal or repository",
        documentation_link="https://docs.openalex.org/api-entities/sources",
    ),
    OpenAlexIDField(param="primary_location.source.host_organization"),
    OpenAlexIDField(param="primary_location.source.host_organization_lineage"),
    OpenAlexIDField(
        param="primary_location.source.publisher_lineage",
        custom_es_field="primary_location.source.host_organization_lineage",
        docstring="Publishers are companies or organizations behind the source where a work is available (such as a journal).",
        documentation_link="https://docs.openalex.org/api-entities/publishers",
    ),
    OpenAlexIDField(param="openalex", custom_es_field="ids.openalex.lower"),
    OpenAlexIDField(param="openalex_id", alias="ids.openalex"),
    OpenAlexIDField(
        param="repository",
        custom_es_field="locations.source.id",
        docstring="The repository that a work is available in",
        documentation_link="https://docs.openalex.org/api-entities/works/filter-works#repository",
    ),
    OpenAlexIDField(param="referenced_works"),
    OpenAlexIDField(
        param="related_to",
        docstring="Related works, based on common concepts the works have.",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#related_works",
    ),
    PhraseField(param="host_venue.publisher"),
    RangeField(param="apc_list.value"),
    RangeField(
        param="apc_list.value_usd",
        docstring="The work's APC (article processing charge) <em>list</em> price (in USD). This is the price listed by the journal's publisher, which may be different than the paid price",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#apc_list",
    ),
    RangeField(param="apc_paid.value"),
    RangeField(
        param="apc_paid.value_usd",
        docstring="The work's APC (article processing charge) <em>paid</em> price (in USD). In some cases, this is different from the journal's list price, and this difference is made public. Otherwise, we assume the paid price is the list price",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#apc_paid",
    ),
    RangeField(
        param="authors_count",
        docstring="The number of authors for the work",
        documentation_link="https://docs.openalex.org/api-entities/works/filter-works#authors_count",
    ),
    RangeField(
        param="cited_by_count",
        docstring="The number of times the work has been cited by another work",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#cited_by_count",
    ),
    RangeField(param="concepts_count"),
    RangeField(
        param="countries_distinct_count",
        docstring="The number of distinct countries represented among the work's authors",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#countries_distinct_count",
    ),
    RangeField(param="institutions_distinct_count"),
    RangeField(
        param="locations_count",
        docstring="The number of distinct online locations we have found for the work",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object/location-object",
    ),
    RangeField(
        param="publication_year",
        docstring="The year that the work was published",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#publication_date",
    ),
    RangeField(param="referenced_works_count"),
    SearchField(
        param="abstract.search",
        custom_es_field="abstract",
        docstring="Free text search within the work's abstract only",
        documentation_link="https://docs.openalex.org/api-entities/works/search-works#search-a-specific-field",
    ),
    SearchField(
        param="default.search",
        index="works",
        docstring="Free text search among the work's title, abstract (when available) and full text (when available)",
        documentation_link="https://docs.openalex.org/how-to-use-the-api/get-lists-of-entities/search-entities",
    ),
    SearchField(param="display_name.search"),
    SearchField(param="fulltext.search", custom_es_field="fulltext"),
    SearchField(
        param="raw_affiliation_string.search",
        custom_es_field="authorships.raw_affiliation_string",
    ),
    SearchField(
        param="title.search",
        custom_es_field="display_name",
        docstring="Free text search within the work's title only",
        documentation_link="https://docs.openalex.org/api-entities/works/search-works#search-a-specific-field",
    ),
    TermField(param="apc_list.currency", custom_es_field="apc_list.currency.keyword"),
    TermField(
        param="apc_list.provenance", custom_es_field="apc_list.provenance.keyword"
    ),
    TermField(param="apc_paid.currency"),
    TermField(
        param="apc_paid.provenance",
        custom_es_field="apc_paid.provenance",
        docstring="The source of our information about the work's APC. Works with OpenAPC data might have more accurate prices for APC paid.",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#apc_paid",
    ),
    TermField(param="author.orcid", alias="authorships.author.orcid"),
    TermField(
        param="authorships.author.orcid",
        docstring="The work's authors, by ORCID",
        documentation_link="https://docs.openalex.org/api-entities/authors/author-object#orcid",
    ),
    TermField(
        param="authorships.countries", custom_es_field="authorships.countries.keyword"
    ),
    TermField(param="authorships.institutions.country_code"),
    TermField(
        param=f"authorships.institutions.continent",
        custom_es_field="authorships.institutions.country_code",
    ),
    TermField(
        param="authorships.institutions.ror",
        docstring="The work's authors' institutional affiliations, using ROR ID",
        documentation_link="https://docs.openalex.org/api-entities/institutions/institution-object#ror",
    ),
    TermField(
        param="authorships.institutions.type",
        docstring='The type of institutions affiliated with the work. For example, universities are type "Education," and hospitals are type "Healthcare".',
        documentation_link="https://docs.openalex.org/api-entities/institutions/institution-object#type",
    ),
    TermField(
        param="best_oa_location.source.issn",
    ),
    TermField(
        param="best_oa_location.license",
        docstring="The work's type of Open Access license (or lack thereof). For example, a Creative Commons license, or a publisher-specific license",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object/location-object#license",
    ),
    TermField(param="best_oa_location.source.type"),
    TermField(
        param="best_oa_location.version",
        docstring="The version of the work that is available Open Access",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object/location-object#version",
    ),
    TermField(param="best_open_version", custom_es_field="locations.version"),
    TermField(param="concepts.wikidata"),
    TermField(param="display_name", custom_es_field="display_name.lower"),
    TermField(
        param="doi",
        alias="ids.doi",
        docstring="The DOI (Digital Object Identifier) for a work",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#doi",
    ),
    TermField(param="doi_starts_with", custom_es_field="ids.doi"),
    TermField(param="fulltext_origin", custom_es_field="fulltext_origin.keyword"),
    TermField(param="ids.mag", custom_es_field="ids.mag"),
    TermField(param="ids.pmid", custom_es_field="ids.pmid"),
    TermField(param="ids.pmcid", custom_es_field="ids.pmcid"),
    TermField(
        param="institutions.country_code",
        alias="authorships.institutions.country_code",
        docstring="The countries represented among the work's institutions",
        documentation_link="https://docs.openalex.org/api-entities/institutions/institution-object#country_code",
    ),
    TermField(
        param="institutions.continent",
        alias="authorships.institutions.country_code",
        docstring="The continents represented among a work's institutions",
        documentation_link="https://docs.openalex.org/api-entities/geo/continents",
    ),
    TermField(param="institutions.ror", alias="authorships.institutions.ror"),
    TermField(param="institutions.type", alias="authorships.institutions.type"),
    TermField(
        param="grants.award_id",
        custom_es_field="grants.award_id.keyword",
        docstring="The award IDs listed in the work's grants",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#grants",
    ),
    TermField(
        param="language",
        custom_es_field="language.keyword",
        docstring="The primary language the work is written in (as detected from titles and abstracts)",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#language",
    ),
    TermField(param="locations.source.issn"),
    TermField(param="locations.license"),
    TermField(param="locations.source.type"),
    TermField(param="locations.version"),
    TermField(param="mag", custom_es_field="ids.mag"),
    TermField(param="oa_status", alias="open_access.oa_status"),
    TermField(
        param="open_access.oa_status",
        docstring="""The work's Open Access (OA) status, such as "gold," "green," or "hybrid".""",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#oa_status",
    ),
    TermField(param="pmid", custom_es_field="ids.pmid"),
    TermField(param="pmcid", custom_es_field="ids.pmcid"),
    TermField(param="primary_location.license"),
    TermField(
        param="primary_location.source.issn",
        docstring="The work's journal, by ISSN",
        documentation_link="https://docs.openalex.org/api-entities/sources/source-object#issn_l",
    ),
    TermField(
        param="primary_location.source.type",
        docstring="The type of source for the work. For example, you can filter for only works in journals, or in repositories.",
        documentation_link="https://docs.openalex.org/api-entities/sources/source-object#type",
    ),
    TermField(param="primary_location.version"),
    TermField(
        param="sustainable_development_goals.id",
        custom_es_field="sustainable_development_goals.id.keyword",
        docstring="The work's relevance to one or more of the United Nations' Sustainable Development Goals",
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#sustainable_development_goals",
    ),
    TermField(
        param="type",
        docstring='Most works are type "Article". You can also filter for books, editorials, and more.',
        documentation_link="https://docs.openalex.org/api-entities/works/work-object#type",
    ),
    TermField(param="type_crossref", custom_es_field="type_crossref.keyword"),
    TermField(param="version", custom_es_field="locations.version"),
]

fields_dict = {f.param: f for f in fields}
