id: concepts
displayName: concepts
displayNameSingular: concept
descr: Abstract ideas works are about (deprecated; superseded by topics)
isNative: true
idRegex: (?i)(?:concepts\/)?(?:https:\/\/openalex\.org\/)?(c\d+)
values: null
