id: continents
displayName: continents
displayNameSingular: continent
descr: Continents
descrFull: These are the continents of the world. Each continent has a unique OpenAlex ID.
isNative: false
idRegex: (?i)(?:https:\/\/openalex\.org\/continents\/|continents\/)(q\d+)
values:
- id: continents/Q15
  display_name: Africa
- id: continents/Q18
  display_name: South America
- id: continents/Q46
  display_name: Europe
- id: continents/Q48
  display_name: Asia
- id: continents/Q49
  display_name: North America
- id: continents/Q51
  display_name: Antarctica
- id: continents/Q55643
  display_name: Oceania
