id: domains
displayName: domains
displayNameSingular: domain
descr: what works are about
descrFull: These are the domains of scholarly works which are the highest level description for a subject
  area of a work. Each domain has a unique OpenAlex ID.
isNative: false
idRegex: (?:https:\/\/openalex\.org\/domains\/|domains\/)(\d+)
values:
- id: domains/3
  display_name: Physical Sciences
- id: domains/2
  display_name: Social Sciences
- id: domains/4
  display_name: Health Sciences
- id: domains/1
  display_name: Life Sciences
