# based on https://github.com/ourresearch/openalex-gui/blob/f30c0e8b0c858914c1c79cbcd6d31f6e7b1e0ecf/src/entityConfigs.js#L0-L1
entity_configs = [
    {
        "id": "works",
        "icon": "mdi-file-document-outline",
        "name": "works",
        "nameSingular": "work",
        "displayName": "works",
        "displayNameSingular": "work",
        "descr": "Scholarly papers, books, datasets, etc.",
        "eg": "On the Electrodynamics of Moving Bodies",
        "placeholder": "Search scholarly papers, books, and more",
        "filterName": "work",
        "filterKey": "ids.openalex",
        "hintVerb": "by",
        "color": "blue",
        "hasAutocomplete": True,
        "isNative": True,
        "hasSerp": True,
        "highlightFilters": [
            {"key": "open_access.is_oa", "value": True, "displayName": "Open Access works"},
            {"key": "institutions.is_global_south", "value": True, "displayName": "from the Global South"},
            {"key": "type", "value": "dataset", "displayName": "datasets"},
        ],
        "idRegex": r"(?i)(?:works\/)?(?:https:\/\/openalex\.org\/)?(w\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "publication_year",
            "type",
            "abstract_inverted_index",
            "primary_location.source.id",
            "",
            "authorships.author.id",
            "authorships.institutions.id",
            "",
            "primary_topic.id",
            "primary_topic.subfield.id",
            "primary_topic.field.id",
            "primary_topic.domain.id",
            "sustainable_development_goals.id",
            "",
            "open_access.oa_status",
            "apc_paid.value_usd",
            "",
            "grants.funder",
            "grants.award_id",
        ],
        "ShowOnTablePage": [
            "display_name",
            "publication_year",
            "type",
            "primary_location.source.id",
            "authorships.author.id",
            "authorships.institutions.id",
            "primary_topic.id",
            "primary_topic.subfield.id",
            "sustainable_development_goals.id",
            "open_access.oa_status",
            "cited_by_count",
            "fwci,"
        ],
        "groupByDefaults": [
            "publication_year",
            "open_access.is_oa",
            "primary_topic.id",
            "keywords",
            "authorships.institutions.lineage",
            "type",
        ],
    },
    {
        "id": "authors",
        "icon": "mdi-account-outline",
        "name": "authors",
        "nameSingular": "author",
        "displayName": "authors",
        "displayNameSingular": "author",
        "descr": "Creators of scholarly works",
        "eg": "Albert Einstein",
        "placeholder": "Search scholarly authors",
        "filterName": "author",
        "filterKey": "authorships.author.id",
        "hintVerb": "at",
        "color": "green",
        "hasAutocomplete": True,
        "isNative": True,
        "hasSerp": True,
        "highlightFilters": [
            {"key": "has_orcid", "value": True, "displayName": "with ORCIDs"},
            {"key": "last_known_institutions.is_global_south", "value": True, "displayName": "from the Global South"},
        ],
        "idRegex": r"(?i)(?:authors\/)?(?:https:\/\/openalex\.org\/)?(a\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "display_name_alternatives",
            "ids.orcid",
            "",
            "last_known_institutions.id",
            "affiliations.institution.id",
        ],
        "ShowOnTablePage": [
            "display_name",
            "display_name_alternatives",
            "ids.orcid",
            "last_known_institutions.id",
        ],
        "groupByDefaults": [
            "last_known_institutions.id",
            "last_known_institutions.country_code",
            "has_orcid",
        ],
    },
    {
        "id": "sources",
        "icon": "mdi-book-open-outline",
        "name": "sources",
        "nameSingular": "source",
        "displayName": "sources",
        "displayNameSingular": "source",
        "descr": "Journals, conferences, and repositories",
        "eg": "The New England Journal of Medicine",
        "placeholder": "Search academic journals & repositories",
        "filterName": "primary_location.source",
        "filterKey": "primary_location.source.id",
        "hintVerb": "published by",
        "color": "orange",
        "hasAutocomplete": True,
        "isNative": True,
        "hasSerp": True,
        "highlightFilters": [
            {"key": "is_oa", "value": True, "displayName": "that are Open Access"},
        ],
        "idRegex": r"(?i)(?:sources\/)?(?:https:\/\/openalex\.org\/)?(s\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "alternate_titles",
            "",
            "type",
            "ids.issn",
            "host_organization",
            ""
            "is_oa",
            "is_in_doaj",
            "apc_usd",
        ],
        "ShowOnTablePage": [
            "display_name",
            "ids.issn",
            "type",
            "host_organization",
            "is_oa",
            "is_in_doaj",
            "apc_usd",
        ],
        "groupByDefaults": [
            "type",
            "host_organization",
            "is_oa",
            "is_in_doaj",
        ],
    },
    {
        "id": "publishers",
        "icon": "mdi-domain",
        "name": "publishers",
        "nameSingular": "publisher",
        "displayName": "publishers",
        "displayNameSingular": "publisher",
        "descr": "Company hosting journals",
        "eg": "Elsevier",
        "placeholder": "Search academic publishers",
        "filterName": "primary_location.source.publisher_lineage",
        "filterKey": "primary_location.source.publisher_lineage",
        "color": "pink",
        "hasAutocomplete": True,
        "isNative": True,
        "idRegex": r"(?i)(?:publishers\/)?(?:https:\/\/openalex\.org\/)?(p\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
        ],
        "ShowOnTablePage": [
            "display_name",
        ],
    },
    {
        "id": "funders",
        "icon": "mdi-cash-multiple",
        "name": "funders",
        "nameSingular": "funder",
        "displayName": "funders",
        "displayNameSingular": "funder",
        "descr": "Organization funding works via grants",
        "eg": "US National Science Foundation",
        "placeholder": "Search research funders",
        "filterName": "grants.funder",
        "filterKey": "grants.funder",
        "color": "brown",
        "hasAutocomplete": True,
        "isNative": True,
        "idRegex": r"(?i)(?:funders\/)?(?:https:\/\/openalex\.org\/)?(f\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name"
        ],
        "ShowOnTablePage": [
            "display_name"
        ],
    },
    {
        "id": "institutions",
        "icon": "mdi-town-hall",
        "name": "institutions",
        "nameSingular": "institution",
        "displayName": "institutions",
        "displayNameSingular": "institution",
        "descr": "Universities and research centers",
        "eg": "Harvard University",
        "placeholder": "Search academic institutions",
        "filterName": "institutions",
        "filterKey": "authorships.institutions.lineage",
        "hintVerb": "in",
        "color": "purple",
        "hasAutocomplete": True,
        "isNative": True,
        "hasSerp": True,
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "display_name_alternatives",
            "ids.ror",
            "parent_institutions",
            "child_institutions",
            "related_institutions",
        ],
        "ShowOnTablePage": [
            "display_name",
            "type",
            "country_code",
            "parent_institutions",
            "child_institutions",
            "ids.ror",
        ],

        "idRegex": r"(?i)(?:institutions\/)?(?:https:\/\/openalex\.org\/)?(i\d+)",
        "groupByDefaults": [
            "country_code",
            "type",
        ],
    },
    {
        "id": "concepts",
        "icon": "mdi-tag-outline",
        "name": "concepts",
        "nameSingular": "concept",
        "displayName": "concepts",
        "displayNameSingular": "concept",
        "descr": "Topics and fields of study",
        "eg": "History",
        "placeholder": "Search topics",
        "filterName": "concepts",
        "filterKey": "concepts.id",
        "hasAutocomplete": True,
        "isNative": True,
        "idRegex": r"(?i)(?:concepts\/)?(?:https:\/\/openalex\.org\/)?(c\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "description",
        ],
        "ShowOnTablePage": [
            "display_name",
            "description",
        ],
    },
    {
        "id": "keywords",
        "icon": "mdi-tag-outline",
        "name": "keywords",
        "nameSingular": "keyword",
        "displayName": "keywords",
        "displayNameSingular": "keyword",
        "descr": "what works are about",
        "eg": "Cardiac imaging",
        "placeholder": "Search keywords",
        "filterName": "keywords",
        "filterKey": "keywords.id",
        "hintVerb": ":",
        "hasAutocomplete": True,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/keywords\/|keywords\/)([a-zA-Z0-9\-]+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
        ],
        "ShowOnTablePage": [
            "display_name",
        ],
    },
    {
        "id": "topics",
        "icon": "mdi-tag-outline",
        "name": "topics",
        "nameSingular": "topic",
        "displayName": "topics",
        "displayNameSingular": "topics",
        "descr": "what works are about",
        "eg": "RNA sequencing",
        "placeholder": "Search topics",
        "filterName": "topics",
        "filterKey": "primary_topic.id",
        "hintVerb": ":",
        "hasAutocomplete": True,
        "isNative": True,
        "idRegex": r"(?i)(?:topics\/)?(?:https:\/\/openalex\.org\/)?(t\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "description",
            "",
            "domain",
            "field",
            "subfield",
            "",
            "siblings",    
        ],
        "ShowOnTablePage": [
            "display_name",
            "description",
            "siblings",
            "subfield",
            "field",
            "domain",
        ],
    },
    {
        "id": "subfields",
        "icon": "mdi-tag-outline",
        "name": "subfields",
        "nameSingular": "subfield",
        "displayName": "subfields",
        "displayNameSingular": "subfield",
        "descr": "what works are about",
        "eg": "Molecular biology",
        "placeholder": "Search subfields",
        "filterName": "subfields",
        "filterKey": "primary_topic.subfield.id",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/subfields\/|subfields\/)(\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "description",
            "",
            "domain",
            "field",
            "",
            "topics",
            "",
            "siblings",
        ],
        "ShowOnTablePage": [
            "display_name",
            "description",
            "topics",
            "siblings",
            "field",
            "domain",
        ],
    },
    {
        "id": "fields",
        "icon": "mdi-tag-outline",
        "name": "fields",
        "nameSingular": "field",
        "displayName": "fields",
        "displayNameSingular": "field",
        "descr": "what works are about",
        "eg": "Computer science",
        "placeholder": "Search fields",
        "filterName": "fields",
        "filterKey": "primary_topic.field.id",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/fields\/|fields\/)(\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "display_name_alternatives",
            "description",
            "",
            "domain",
            "",
            "subfields",
            "siblings",
        ],
        "ShowOnTablePage": [
            "display_name",
            "description",
            "subfields",
            "siblings",
            "domain",
        ],
    },
    {
        "id": "domains",
        "icon": "mdi-tag-outline",
        "name": "domains",
        "nameSingular": "domain",
        "displayName": "domains",
        "displayNameSingular": "domain",
        "descr": "what works are about",
        "eg": "Life sciences",
        "placeholder": "Search domains",
        "filterName": "domains",
        "filterKey": "primary_topic.domain.id",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/domains\/|domains\/)(\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "display_name_alternatives",
            "description",
            "",
            "fields",
            "",
            "siblings",
        ],
        "ShowOnTablePage": [
            "display_name",
            "description",
            "fields",
            "siblings",
        ],
    },
    {
        "id": "sdgs",
        "icon": "mdi-sprout-outline",
        "name": "sdgs",
        "nameSingular": "sdg",
        "displayName": "Sustainable Development Goals",
        "displayNameSingular": "Sustainable Development Goal",
        "descr": "Relevant UN SDGs",
        "eg": "Clean water and sanitation",
        "placeholder": "Search SDGs",
        "filterName": "Sustainable Development Goals",
        "filterKey": "sustainable_development_goals.id",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/sdgs\/|sdgs\/)(\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
        ],
        "ShowOnTablePage": [
            "display_name",
        ],
    },
    {
        "id": "countries",
        "icon": "mdi-earth",
        "name": "countries",
        "nameSingular": "country",
        "displayName": "countries",
        "displayNameSingular": "country",
        "descr": "Countries",
        "eg": "Nigeria",
        "placeholder": "Search countries",
        "filterName": "countries",
        "filterKey": "authorships.countries",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/countries\/|countries\/)([a-zA-Z]{2})",
        "ShowOnEntityPage": [
            "id",
            "display_name",
        ],
        "ShowOnTablePage": [
            "display_name",
        ],
    },
    {
        "id": "continents",
        "icon": "mdi-earth",
        "name": "continents",
        "nameSingular": "continent",
        "displayName": "continents",
        "displayNameSingular": "continent",
        "descr": "Continents",
        "eg": "Africa",
        "placeholder": "Search continents",
        "filterName": "continent",
        "filterKey": "authorships.institutions.continent",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?i)(?:https:\/\/openalex\.org\/continents\/|continents\/)(q\d+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "countries",
        ],
        "ShowOnTablePage": [
            "display_name",
            "countries",
        ],
    },
    {
        "id": "languages",
        "icon": "mdi-translate",
        "name": "languages",
        "nameSingular": "language",
        "displayName": "languages",
        "displayNameSingular": "language",
        "descr": "Languages",
        "eg": "Swahili",
        "placeholder": "Search languages",
        "filterName": "languages",
        "filterKey": "language",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/languages\/|languages\/)([a-zA-Z]{2})",
        "ShowOnEntityPage": [
            "id",
            "display_name",
        ],
        "ShowOnTablePage": [
            "display_name",
        ],
    },
    {
        "id": "types",
        "icon": "mdi-shape-outline",
        "name": "types",
        "nameSingular": "type",
        "displayName": "types",
        "displayNameSingular": "type",
        "descr": "Work type",
        "eg": "article",
        "placeholder": "Search work types",
        "filterName": "type",
        "filterKey": "type",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/types\/|types\/)([a-zA-Z\-]+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "description",
            "crossref_types",
        ],
        "ShowOnTablePage": [
            "display_name",
            "description",
        ],
    },
    {
        "id": "source-types",
        "icon": "mdi-shape-outline",
        "name": "source-types",
        "nameSingular": "source type",
        "displayName": "source types",
        "displayNameSingular": "source type",
        "descr": "Source type",
        "eg": "journal",
        "placeholder": "Search source types",
        "filterName": "source type",
        "filterKey": "primary_location.source.type",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/source-types\/|source-types\/)([a-zA-Z\-]+)",
        "ShowOnEntityPage": [
            "id",
            "display_name",
            "description",
        ],
        "ShowOnTablePage": [
            "display_name",
            "description",
        ],
    },
    {
        "id": "institution-types",
        "icon": "mdi-shape-outline",
        "name": "institution-types",
        "nameSingular": "institution type",
        "displayName": "institution types",
        "displayNameSingular": "institution type",
        "descr": "institution type",
        "eg": "company",
        "placeholder": "Search institution types",
        "filterName": "institution type",
        "filterKey": "authorships.institutions.type",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/institution-types\/|institution-types\/)([a-zA-Z\-]+)",
        "ShowOnEntityPage": [
            "id",
            "display_name"
        ],
        "ShowOnTablePage": [
            "display_name"
        ],
    },
    {
        "id": "licenses",
        "icon": "mdi-lock-open-outline",
        "name": "licenses",
        "nameSingular": "license",
        "displayName": "licenses",
        "displayNameSingular": "license",
        "descr": "license of best open copy",
        "eg": "CC-BY",
        "placeholder": "Search licenses",
        "filterName": "institution type",
        "filterKey": "best_oa_location.license",
        "hasAutocomplete": False,
        "isNative": False,
        "idRegex": r"(?:https:\/\/openalex\.org\/licenses\/|licenses\/)([a-zA-Z0-9\-]+)",
        "ShowOnEntityPage": [
            "id",
            "display_name"
            "descr",
        ],
        "ShowOnTablePage": [
            "display_name"
        ],
    },
]

entity_configs_dict = {config['id']: config for config in entity_configs}
