id: funders
displayName: funders
displayNameSingular: funder
descr: Organization funding works via grants
descrFull: These are the organizations that fund research works via grants. Each funder has a unique OpenAlex
  ID.
isNative: true
idRegex: (?i)(?:funders\/)?(?:https:\/\/openalex\.org\/)?(f\d+)
values: null
