id: institutions
displayName: institutions
displayNameSingular: institution
descr: Institutions (universities and research centers)
descrFull: The institution (university or research center) where an author is affiliated. All institutions
  have a Research Organization Registry (ROR) ID.
isNative: true
idRegex: (?i)(?:institutions\/)?(?:https:\/\/openalex\.org\/)?(i\d+)
values: null
