id: keywords
displayName: keywords
displayNameSingular: keyword
descr: what works are about
descrFull: Keywords are the lowest level of categorization for works. They are used to specifically describe
  a work.
isNative: false
idRegex: (?:https:\/\/openalex\.org\/keywords\/|keywords\/)([a-zA-Z0-9\-]+)
values: null
