# based on https://github.com/ourresearch/openalex-gui/blob/8c01677c30104bf994c841fe9597ad0af6631a4b/src/facetConfigs.js#L58-L59
property_configs = [
    # works: WASPFIC.
    {
        "key": "id",
        "id": "id",
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "works",
        "objectEntity": "works",
        "displayName": "Work",
        "isSingleWork": True,
        "isId": True,
        "type": "select",
        "newType": "string",
        "category": "ids",
        "actions": [""],
        "icon": "mdi-file-document-outline",
        "extractFn": "(entity) => entity.id",
    },
    {
        "key": "doi",
        "id": "doi",
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "works",
        "objectEntity": "works",
        "displayName": "DOI",
        "isSingleWork": True,
        "isId": True,
        "type": "select",
        "newType": "string",
        "category": "ids",
        "actions": [],
        "icon": "mdi-file-document-outline",
        "extractFn": "(entity) => entity.doi",
    },
    {
        "key": "concepts.id",
        "id": "concepts.id",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "concept",
        "entityId": "concepts",
        "objectEntity": "concepts",
        "type": "select",
        "newType": "entity",
        "category": "other",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-tag-outline",
        "extractFn": "(entity) => entity.concepts",
    },
    {
        "key": "primary_topic.id",
        "id": "primary_topic.id",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "topic",
        "entityId": "topics",
        "objectEntity": "topics",
        "type": "select",
        "newType": "entity",
        "category": "other",
        "actions": [
            "filter",
            "group_by",
        ],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
        "extractFn": "(entity) => entity.primary_topic",
    },
    {
        "key": "keywords.id",
        "id": "keywords.id",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "keyword",
        "entityId": "keywords",
        "objectEntity": "keywords",
        "type": "select",
        "newType": "entity",
        "category": "other",
        "actions": [
            "filter",
            "group_by",
        ],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
        "extractFn": "(entity) => entity.keywords",
    },
    {
        "key": "primary_topic.subfield.id",
        "id": "primary_topic.subfield.id",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "subfield",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "type": "select",
        "newType": "entity",
        "category": "other",
        "actions": [
            "filter",
            "group_by",
        ],
        "actionsPopular": [],
        "icon": "mdi-tag-outline",
        "extractFn": "(entity) => entity.primary_topic.subfield",
    },
    {
        "key": "primary_topic.field.id",
        "id": "primary_topic.field.id",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "field",
        "entityId": "fields",
        "objectEntity": "fields",
        "type": "select",
        "newType": "entity",
        "category": "other",
        "actions": [
            "filter",
            "group_by",
        ],
        "actionsPopular": [],
        "icon": "mdi-tag-outline",
        "extractFn": "(entity) => entity.primary_topic.field",
    },
    {
        "key": "primary_topic.domain.id",
        "id": "primary_topic.domain.id",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "domain",
        "entityId": "domains",
        "objectEntity": "domains",
        "type": "select",
        "newType": "entity",
        "category": "other",
        "actions": [
            "filter",
            "group_by",
        ],
        "actionsPopular": [],
        "icon": "mdi-tag-outline",
        "extractFn": "(entity) => entity.primary_topic.domain",
    },
    {
        "key": "grants.funder",
        "id": "grants.funder",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "funder",
        "entityId": "funders",
        "objectEntity": "funders",
        "type": "select",
        "newType": "entity",
        "category": "other",
        "actions": [
            "filter",
            "group_by",
        ],
        "icon": "mdi-cash-multiple",
        "extractFn": "(entity) => entity.grants.map(grant => { return { id: grant.funder, display_name: grant.funder_display_name, } })",
    },
    {
        "key": "grants.award_id",
        "id": "grants.award_id",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "grant ID",
        "type": "search",
        "newType": "string",
        "category": "other",
        "actions": [],
        "icon": "mdi-cash-multiple",
        "extractFn": "(entity) => entity.grants.map(grant => grant.award_id)",
    },
    {
        "key": "authorships.institutions.id",
        "id": "authorships.institutions.id",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "institution",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "type": "select",
        "newType": "entity",
        "category": "institution",
        "actions": [
            "filter",
            "group_by",
        ],
        "actionsPopular": [
            "filter",
            "group_by",
        ],
        "icon": "mdi-town-hall",
        "extractFn": "(entity) => { const nested = entity.authorships.map(authorship => { return authorship.institutions }); return uniqueObjects(nested.flat()) }",
    },
    {
        "key": "authorships.institutions.ror",
        "id": "authorships.institutions.ror",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "displayName": "ROR ID",
        "isId": True,
        "type": "entity",
        "newType": "entity",
        "category": "ids",
        "actions": [],
        "icon": "mdi-town-hall",
        "extractFn": "(entity) => { const nested = entity.authorships.map(authorship => { return authorship.institutions.map(insti => insti.ror) }); return nested.flat() }",
    },
    {
        "key": "authorships.author.id",
        "id": "authorships.author.id",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "author",
        "entityId": "authors",
        "objectEntity": "authors",
        "type": "select",
        "newType": "entity",
        "category": "author",
        "actions": [
            "filter",
            "group_by",
        ],
        "actionsPopular": [
            "filter",
            "group_by",
        ],
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => { return entity.authorships.map(authorship => { return authorship.author }) }",
    },
    {
        "key": "authorships.author.orcid",
        "id": "authorships.author.orcid",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "ORCID",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "category": "ids",
        "actions": [],
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => { return entity.authorships.map(authorship => { return authorship.author.orcid }) }",
    },
    # works: search
    {
        "key": "default.search",
        "id": "default.search",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "fulltext",
        "type": "search",
        "newType": "string",
        "actions": [
            "filter",
        ],
        "actionsPopular": [
            "filter",
        ],
        "category": "other",
        "icon": "mdi-magnify",
    },
    {
        "key": "title_and_abstract.search",
        "id": "title_and_abstract.search",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "title & abstract",
        "type": "search",
        "newType": "string",
        "actions": [
            "filter",
        ],
        "actionsPopular": [],
        "category": "other",
        "icon": "mdi-magnify",
    },
    {
        "key": "display_name.search",
        "id": "display_name.search",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "title",
        "actions": [
            "filter",
        ],
        "actionsPopular": [],
        "type": "search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    {
        "key": "raw_affiliation_strings.search",
        "id": "raw_affiliation_strings.search",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "raw affiliation string",
        "type": "search",
        "newType": "string",
        "actions": [
            "filter",
        ],
        "actionsPopular": [
            "",
        ],
        "category": "other",
        "icon": "mdi-magnify",
    },
    {
        "key": "doi_starts_with",
        "id": "doi_starts_with",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "DOI prefix",
        "type": "search",
        "newType": "string",
        "actions": [
            "filter",
        ],
        "actionsPopular": [],
        "category": "other",
        "icon": "mdi-magnify",
        "verb": "starts with",
    },
    # this is a wierd one, still working it into the schema
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "title",
        "type": "search",
        "newType": "string",
        "actions": [
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "category": "other",
        "icon": "mdi-file-document-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "title",
        "id": "title",
        "isColumnMandatory": False,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "title",
        "type": "search",
        "newType": "string",
        "actions": [
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "category": "other",
        "icon": "mdi-file-document-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "has_abstract",
        "id": "has_abstract",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "Abstract available",
        "type": "boolean",
        "newType": "boolean",
        "actions": ["filter"],
        "icon": "mdi-file-document-outline",
    },
    # works: authors
    {
        "key": "authors_count",
        "id": "authors_count",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "authors count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "author",
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.authors_count",
    },
    {
        "key": "corresponding_author_ids",
        "id": "corresponding_author_ids",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "corresponding author",
        "type": "select",
        "newType": "entity",
        "category": "author",
        "actions": [
            "filter",
            "group_by",
        ],
        "icon": "mdi-email-outline",
    },
    # works: open access
    {
        "key": "open_access.is_oa",
        "id": "open_access.is_oa",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "open access",
        "type": "boolean",
        "newType": "boolean",
        "actions": [
            "filter",
            "column",
            "group_by",
        ],
        "actionsPopular": [
            "filter",
            "column",
            "group_by",
        ],
        "category": "open access",
        "icon": "mdi-lock-open-outline",
    },
    {
        "key": "best_oa_location.license",
        "id": "best_oa_location.license",
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "licenses",
        "objectEntity": "licenses",
        "displayName": "license",
        "type": "select",
        "newType": "entity",
        # actions: [],
        "actions": ["filter", "column", "group_by"],
        "category": "open access",
        "icon": "mdi-lock-open-outline",
        "displayNullAs": "All rights reserved",
    },
    # disabled, waiting for entity
    {
        "key": "open_access.oa_status",
        "id": "open_access.oa_status",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "Open Access status",
        "type": "select",
        "newType": "entity",
        # actions: ["filter", "column", "group_by",],
        "actions": [],
        "category": "open access",
        "icon": "mdi-lock-open-outline",
        "extractFn": "(entity) => entity.open_access.oa_status",
    },
    {
        "key": "best_oa_location.is_accepted",
        "id": "best_oa_location.is_accepted",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "open access accepted",
        "type": "boolean",
        "newType": "boolean",
        "actions": [
            "filter",
            "column",
            "group_by",
        ],
        "category": "open access",
        "icon": "mdi-lock-open-outline",
    },
    {
        "key": "best_oa_location.is_published",
        "id": "best_oa_location.is_published",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "open access published",
        "type": "boolean",
        "newType": "boolean",
        "actions": [
            "filter",
            "column",
            "group_by",
        ],
        "category": "open access",
        "icon": "mdi-lock-open-outline",
    },
    {
        "key": "apc_paid.value_usd",
        "id": "apc_paid.value_usd",
        "isCurrency": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "APC paid (est)",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
        ],
        "icon": "mdi-cash",
        "extractFn": "(entity) => entity.apc_paid.value_usd",
    },
    # works: institutions:
    {
        "key": "authorships.countries",
        "id": "authorships.countries",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "countries",
        "objectEntity": "countries",
        "displayName": "Country",
        "type": "select",
        "newType": "entity",
        "isCountry": True,
        "actions": [
            "filter",
            "column",
            "group_by",
        ],
        "actionsPopular": [
            "group_by",
        ],
        "category": "institution",
        "icon": "mdi-earth",
    },
    {
        "key": "countries_distinct_count",
        "id": "countries_distinct_count",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "countries count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "examples": ["1", "2-", "2-10"],
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "category": "institution",
        "icon": "mdi-earth",
    },
    {
        "key": "institutions_distinct_count",
        "id": "institutions_distinct_count",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "institutions count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "examples": ["1", "2-", "2-10"],
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "category": "institution",
        "icon": "mdi-earth",
    },
    {
        "key": "authorships.institutions.continent",
        "id": "authorships.institutions.continent",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "continents",
        "objectEntity": "continents",
        "displayName": "Continent",
        "type": "select",
        "newType": "entity",
        "actions": [
            "filter",
            "column",
            "group_by",
        ],
        "actionsPopular": [],
        "icon": "mdi-earth",
    },
    {
        "key": "institutions.is_global_south",
        "id": "institutions.is_global_south",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "from Global South",
        "type": "boolean",
        "newType": "boolean",
        "actions": [
            "filter",
            "column",
            "group_by",
        ],
        "category": "institution",
        "icon": "mdi-earth",
        # icon: "mdi-town-hall",
    },
    {
        "key": "authorships.institutions.type",
        "id": "authorships.institutions.type",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "institution type",
        "category": "institution",
        "type": "select",
        "newType": "entity",
        "actions": [
            "filter",
            "group_by",
        ],
        "icon": "mdi-town-hall",
    },
    {
        "key": "corresponding_institution_ids",
        "id": "corresponding_institution_ids",
        "isList": True,
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "displayName": "corresponding institution",
        "category": "institution",
        "type": "select",
        "newType": "entity",
        "actions": [
            "filter",
            "group_by",
        ],
        "icon": "mdi-email-outline",
    },
    # works: primary source
    {
        "key": "primary_location.source.id",
        "id": "primary_location.source.id",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "source",
        "entityId": "sources",
        "objectEntity": "sources",
        "type": "select",
        "newType": "entity",
        "category": "source",
        "actions": [
            "filter",
            "group_by",
        ],
        "icon": "mdi-book-open-outline",
        "extractFn": "(entity) => entity.primary_location.source",
    },
    {
        "key": "primary_location.source.issn",
        "id": "primary_location.source.issn",
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "sources",
        "objectEntity": "sources",
        "displayName": "ISSN",
        "isId": True,
        "type": "entity",
        "newType": "entity",
        "category": "ids",
        "actions": [],
        "icon": "mdi-book-open-outline",
    },
    {
        "key": "primary_location.source.type",
        "id": "primary_location.source.type",
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "sources",
        "objectEntity": "sources",
        "displayName": "source type",
        "type": "select",
        "newType": "entity",
        "category": "source",
        "actions": ["filter", "column", "group_by"],
        "icon": "mdi-book-open-outline",
    },
    {
        "key": "primary_location.source.is_in_doaj",
        "id": "primary_location.source.is_in_doaj",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "indexed by DOAJ",
        "type": "boolean",
        "newType": "boolean",
        "category": "source",
        "actions": ["filter", "group_by"],
        "icon": "mdi-book-open-outline",
    },
    {
        "key": "primary_location.source.is_oa",
        "id": "primary_location.source.is_oa",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "in OA source",
        "type": "boolean",
        "newType": "boolean",
        "category": "source",
        "actions": ["filter", "column", "group_by"],
        "icon": "mdi-book-open-outline",
    },
    {
        "key": "primary_location.source.publisher_lineage",
        "id": "primary_location.source.publisher_lineage",
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "publishers",
        "objectEntity": "publishers",
        "displayName": "publisher",
        "type": "select",
        "newType": "entity",
        "category": "source",
        "actions": ["filter", "group_by"],
        "icon": "mdi-domain",
    },
    {
        "key": "repository",
        "id": "repository",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "repository",
        "entityId": "sources",
        "objectEntity": "sources",
        "type": "select",
        "newType": "entity",
        "category": "source",
        "actions": ["filter", "group_by"],
        "icon": "mdi-book-open-outline",
    },
    {
        "key": "open_access.any_repository_has_fulltext",
        "id": "open_access.any_repository_has_fulltext",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "has repository fulltext",
        "type": "boolean",
        "newType": "boolean",
        "category": "source",
        "actions": ["filter", "column", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "key": "type",
        "id": "type",
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "types",
        "objectEntity": "types",
        "displayName": "type",
        "type": "select",
        "isExternalId": True,
        "externalIdPrefix": "work-types",
        "newType": "entity",
        "category": "other",
        "actions": ["filter", "column", "group_by"],
        "actionsPopular": ["filter", "column", "group_by"],
        "icon": "mdi-shape-outline",
        "extractFn": "(entity) => entity.type",
    },
    {
        "key": "abstract_inverted_index",
        "id": "abstract_inverted_index",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "Abstract",
        "type": "search",
        "newType": "string",
        "actions": [],
        "icon": "mdi-text",
        "extractFn": "(entity) => {\n                if (!entity?.open_access?.is_oa) return\n                return unravel(entity.abstract_inverted_index)\n            }",
    },
    {
        "key": "publication_year",
        "id": "publication_year",
        "isYear": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "year",
        "isDate": True,
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "examples": ["1999", "1999-", "1999-2020"],
        "category": "other",
        "actions": ["filter", "sort", "column", "group_by"],
        "actionsPopular": ["filter", "sort", "column", "group_by"],
        "icon": "mdi-calendar-range",
        "extractFn": "(entity) => entity.publication_year",
    },
    {
        "key": "apc_sum",
        "id": "apc_sum",
        "isCurrency": True,
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "APC sum",
        "type": "sum",
        "newType": "sum",
        "category": "other",
        "actions": ["group_by"],
        "actionsPopular": ["group_by"],
        "icon": "mdi-cash",
    },
    {
        "key": "cited_by_count_sum",
        "id": "cited_by_count_sum",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "Citations sum",
        "type": "sum",
        "newType": "sum",
        "category": "other",
        "actions": ["group_by"],
        "actionsPopular": ["group_by"],
        "icon": "mdi-format-quote-close",
    },
    {
        "key": "publication_date",
        "id": "publication_date",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "date",
        "isDate": True,
        "type": "range",
        "newType": "number",
        "actions": ["sort"],
        "sortByValue": True,
        "category": "other",
        "examples": ["1999", "1999-", "1999-2020"],
        "icon": "mdi-calendar-range",
    },
    {
        "key": "has_doi",
        "id": "has_doi",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "indexed by Crossref",
        "type": "boolean",
        "newType": "boolean",
        "category": "ids",
        "actions": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "key": "mag_only",
        "id": "mag_only",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "indexed by MAG only",
        "type": "boolean",
        "newType": "boolean",
        "category": "ids",
        "actions": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "key": "has_orcid",
        "id": "has_orcid",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "indexed by ORCID",
        "type": "boolean",
        "newType": "boolean",
        "actions": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "key": "has_pmid",
        "id": "has_pmid",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "indexed by PubMed",
        "type": "boolean",
        "newType": "boolean",
        "category": "ids",
        "actions": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "key": "is_retracted",
        "id": "is_retracted",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "retracted",
        "type": "boolean",
        "newType": "boolean",
        "category": "other",
        "actions": ["filter", "column", "group_by"],
        "icon": "mdi-close-octagon",
    },
    {
        "key": "language",
        "id": "language",
        "entityId": "languages",
        "objectEntity": "languages",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "language",
        "type": "select",
        "newType": "entity",
        "displayNullAs": "Unknown",
        "category": "other",
        "actions": ["filter", "column", "group_by"],
        "actionsPopular": ["column", "group_by"],
        "icon": "mdi-translate",
    },
    {
        "key": "sustainable_development_goals.id",
        "id": "sustainable_development_goals.id",
        "isList": True,
        "entityId": "sdgs",
        "objectEntity": "sdgs",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "Sustainable Development Goal",
        "type": "select",
        "newType": "entity",
        "displayNullAs": "Unknown",
        "category": "other",
        "actions": ["filter", "group_by"],
        "icon": "mdi-sprout-outline",
        "extractFn": "(entity) => entity.sustainable_development_goals",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "citation count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-format-quote-close",
    },
    {
        "key": "referenced_works_count",
        "id": "referenced_works_count",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "references count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column"],
        "actionsPopular": [],
        "icon": "mdi-format-quote-close",
    },
    {
        "key": "cited_by_percentile_year.min",
        "id": "cited_by_percentile_year.min",
        "entityType": "works",
        "subjectEntity": "works",
        "displayName": "Citation percentile (year)",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-format-quote-close",
    },
    {
        "key": "cited_by",
        "id": "cited_by",
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "works",
        "objectEntity": "works",
        "displayName": "cited by",
        "type": "select",
        "newType": "entity",
        "category": "citation",
        "actions": [],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    {
        "key": "referenced_works",
        "id": "referenced_works",
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "works",
        "isList": True,
        "objectEntity": "works",
        "displayName": "cites",
        "type": "select",
        "newType": "string",
        "category": "citation",
        "actions": [],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.referenced_works.length",
    },
    {
        "key": "related_works",
        "id": "related_works",
        "entityType": "works",
        "subjectEntity": "works",
        "entityId": "works",
        "objectEntity": "works",
        "displayName": "related to",
        "type": "select",
        "isList": True,
        "newType": "string",
        "category": "other",
        "actions": ["filter"],
        "isHidden": True,
        "icon": "mdi-book-open-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.related_works.length",
    },
    # authors
    {
        "key": "id",
        "id": "id",
        "entityType": "authors",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "author",
        "type": "select",
        "newType": "string",
        "actions": [],
        "actionsPopular": [],
        "isId": True,
        "icon": "mdi-account-outline",
    },
    {
        "key": "ids.orcid",
        "id": "ids.orcid",
        "entityType": "authors",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "ORCID",
        "isId": True,
        "type": "select",
        "newType": "string",
        "icon": "mdi-account-outline",
        "extractFn": "(e) => e.ids.orcid",
    },
    {
        "key": "default.search",
        "id": "default.search",
        "entityType": "authors",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-magnify",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "authors",
        "subjectEntity": "authors",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "affiliations.institution.id",
        "id": "affiliations.institution.id",
        "isList": True,
        "entityType": "authors",
        "subjectEntity": "authors",
        "displayName": "Past institutions",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "type": "select",
        "newType": "entity",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter"],
        "icon": "mdi-town-hall",
        "extractFn": "(entity) => entity.affiliations.map(affil => affil.institution)",
    },
    {
        "key": "affiliations.institution.type",
        "id": "affiliations.institution.type",
        "isList": True,
        "entityType": "authors",
        "subjectEntity": "authors",
        "entityId": "institution-types",
        "objectEntity": "institution-types",
        "displayName": "Past institutions type",
        "type": "select",
        "newType": "entity",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "key": "last_known_institutions.id",
        "id": "last_known_institutions.id",
        "isList": True,
        "entityType": "authors",
        "subjectEntity": "authors",
        "displayName": "institution",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "type": "select",
        "newType": "entity",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-town-hall",
        "extractFn": "(entity) => entity.last_known_institutions",
    },
    {
        "key": "last_known_institutions.country_code",
        "id": "last_known_institutions.country_code",
        "isList": True,
        "entityType": "authors",
        "subjectEntity": "authors",
        "entityId": "countries",
        "objectEntity": "countries",
        "displayName": "institution country",
        "type": "select",
        "newType": "entity",
        "isCountry": True,
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-earth",
        "extractFn": "(entity) => entity.last_known_institutions.map(insti => insti.institution)",
    },
    {
        "key": "last_known_institutions.type",
        "id": "last_known_institutions.type",
        "isList": True,
        "entityType": "authors",
        "subjectEntity": "authors",
        "entityId": "institution-types",
        "objectEntity": "institution-types",
        "displayName": "Institution type",
        "type": "select",
        "newType": "entity",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "key": "has_orcid",
        "id": "has_orcid",
        "entityType": "authors",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "Has an ORCID",
        "type": "boolean",
        "newType": "boolean",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name_alternatives",
        "id": "display_name_alternatives",
        "isList": True,
        "entityType": "authors",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "alternate names",
        "type": "select",
        "newType": "string",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-town-hall",
        "extractFn": "(entity) => entity.display_name_alternatives",
    },
    # authors: summary_stats
    {
        "key": "summary_stats.h_index",
        "id": "summary_stats.h_index",
        "entityType": "authors",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "h-index",
        "type": "range",
        "newType": "number",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-chart-line",
        "extractFn": "(entity) => entity.summary_stats.h_index",
    },
    {
        "key": "summary_stats.i10_index",
        "id": "summary_stats.i10_index",
        "entityType": "authors",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "i10-index",
        "type": "range",
        "newType": "number",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-chart-line",
        "extractFn": "(entity) => entity.summary_stats.i10_index",
    },
    # sources
    {
        "key": "id",
        "id": "id",
        "entityType": "sources",
        "subjectEntity": "sources",
        "entityId": "sources",
        "objectEntity": "sources",
        "displayName": "Source",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-book-open-outline",
    },
    {
        "key": "default.search",
        "id": "default.search",
        "entityType": "sources",
        "subjectEntity": "sources",
        "entityId": "sources",
        "objectEntity": "sources",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-magnify",
    },
    {
        "key": "ids.issn",
        "id": "ids.issn",
        "entityType": "sources",
        "subjectEntity": "sources",
        "entityId": "sources",
        "objectEntity": "sources",
        "displayName": "ISSNs",
        "isId": True,
        "type": "entity",
        "newType": "entity",
        "icon": "mdi-book-open-outline",
        "extractFn": "(e) => e.issn",
    },
    {
        "key": "display_name.search",
        "id": "display_name.search",
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "Title search",
        "type": "search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "publisher",
        "id": "publisher",
        "entityType": "sources",
        "subjectEntity": "sources",
        "entityId": "publishers",
        "objectEntity": "publishers",
        "displayName": "Publisher",
        "type": "select",
        "newType": "entity",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-domain",
        "extractFn": "(e) => {'id': e.host_organization, 'display_name': e.host_organization_name} if e.type == 'journal' else None",
    },
    {
        "key": "type",
        "id": "type",
        "entityType": "sources",
        "subjectEntity": "sources",
        "entityId": "source-types",
        "objectEntity": "source-types",
        "displayName": "Source type",
        "type": "select",
        "newType": "entity",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
        "extractFn": "(e) => e.type",
    },
    {
        "key": "apc_usd",
        "id": "apc_usd",
        "isCurrency": True,
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "Article Processing Charge",
        "type": "range",
        "newType": "number",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-cash",
        "extractFn": "(e) => '$' + (e.apc_usd ? e.apc_usd.toLocaleString() : '')",
    },
    {
        "key": "is_oa",
        "id": "is_oa",
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "Fully open access",
        "type": "boolean",
        "newType": "boolean",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-lock-open-outline",
        "extractFn": "(e) => e.is_oa",
    },
    {
        "key": "is_in_doaj",
        "id": "is_in_doaj",
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "In DOAJ",
        "type": "boolean",
        "newType": "boolean",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-lock-open-outline",
        "extractFn": "(entity) => entity.is_in_doaj",
    },
    {
        "key": "alternate_titles",
        "id": "alternate_titles",
        "isList": True,
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "alternate names",
        "type": "select",
        "newType": "entity",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-book-open-outline",
        "extractFn": "(entity) => entity.alternate_titles",
    },
    # sources: summary_stats
    {
        "key": "summary_stats.2yr_mean_citedness",
        "id": "summary_stats.2yr_mean_citedness",
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "2yr mean citedness",
        "type": "range",
        "newType": "number",
        "actions": ["filter", "sort"],
        "actionsPopular": ["filter", "sort"],
        "icon": "mdi-chart-line",
        "extractFn": "(entity) => entity.summary_stats['2yr_mean_citedness']",
    },
    {
        "key": "summary_stats.h_index",
        "id": "summary_stats.h_index",
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "h-index",
        "type": "range",
        "newType": "number",
        "actions": ["filter"],
        "actionsPopular": [],
        "icon": "mdi-chart-line",
        "extractFn": "(entity) => entity.summary_stats.h_index",
    },
    {
        "key": "summary_stats.i10_index",
        "id": "summary_stats.i10_index",
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "i10-index",
        "type": "range",
        "newType": "number",
        "actions": ["filter"],
        "actionsPopular": [],
        "icon": "mdi-chart-line",
        "extractFn": "(entity) => entity.summary_stats.i10_index",
    },
    # publishers
    {
        "key": "id",
        "id": "id",
        "entityType": "publishers",
        "subjectEntity": "publishers",
        "entityId": "publishers",
        "objectEntity": "publishers",
        "displayName": "Publisher",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-domain",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "publishers",
        "subjectEntity": "publishers",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "display_name.search",
        "id": "display_name.search",
        "entityType": "publishers",
        "subjectEntity": "publishers",
        "displayName": "Name search",
        "type": "search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    # funders
    {
        "key": "id",
        "id": "id",
        "entityType": "funders",
        "subjectEntity": "funders",
        "entityId": "funders",
        "objectEntity": "funders",
        "displayName": "Funder",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-cash-multiple",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "funders",
        "subjectEntity": "funders",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "display_name.search",
        "id": "display_name.search",
        "entityType": "funders",
        "subjectEntity": "funders",
        "displayName": "Name search",
        "type": "search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    # institutions
    {
        "key": "id",
        "id": "id",
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "displayName": "Institution",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-town-hall",
    },
    {
        "key": "default.search",
        "id": "default.search",
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-magnify",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "ids.ror",
        "id": "ids.ror",
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "displayName": "ROR",
        "isId": True,
        "type": "select",
        "newType": "entity",
        "icon": "mdi-town-hall",
        "extractFn": "(e) => e.ids.ror",
    },
    {
        "key": "display_name.search",
        "id": "display_name.search",
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "displayName": "Name search",
        "type": "search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    {
        "key": "country_code",
        "id": "country_code",
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "entityId": "countries",
        "objectEntity": "countries",
        "displayName": "Country",
        "type": "select",
        "newType": "entity",
        "isCountry": True,
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-earth",
    },
    {
        "key": "type",
        "id": "type",
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "entityId": "institution-types",
        "objectEntity": "institution-types",
        "displayName": "Institution type",
        "type": "select",
        "newType": "entity",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "key": "x_concepts.id",
        "id": "x_concepts.id",
        "isList": True,
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "displayName": "Concepts",
        "entityId": "concepts",
        "objectEntity": "concepts",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name_alternatives",
        "id": "display_name_alternatives",
        "isList": True,
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "displayName": "alternate names",
        "type": "select",
        "newType": "string",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-town-hall",
        "extractFn": "(entity) => entity.display_name_alternatives",
    },
    {
        "key": "parent_institutions",
        "id": "parent_institutions",
        "isList": True,
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "displayName": "parent institutions",
        "type": "select",
        "newType": "entity",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-town-hall",
        "extractFn": "(entity) => entity.associated_institutions.filter(i => i.relationship === 'parent')",
    },
    {
        "key": "child_institutions",
        "id": "child_institutions",
        "isList": True,
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "displayName": "child institutions",
        "type": "select",
        "newType": "entity",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-town-hall",
        "extractFn": "(entity) => entity.associated_institutions.filter(i => i.relationship === 'child')",
    },
    {
        "key": "related_institutions",
        "id": "related_institutions",
        "isList": True,
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "displayName": "related institutions",
        "type": "select",
        "newType": "entity",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-town-hall",
        "extractFn": "(entity) => entity.associated_institutions.filter(i => i.relationship === 'related')",
    },
    # institutions: summary_stats
    # none for now.
    # concepts
    {
        "key": "id",
        "id": "id",
        "entityType": "concepts",
        "subjectEntity": "concepts",
        "entityId": "concepts",
        "objectEntity": "concepts",
        "displayName": "Concept",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "concepts",
        "subjectEntity": "concepts",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "display_name.search",
        "id": "display_name.search",
        "entityType": "concepts",
        "subjectEntity": "concepts",
        "displayName": "Name search",
        "type": "search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    {
        "key": "level",
        "id": "level",
        "entityType": "concepts",
        "subjectEntity": "concepts",
        "displayName": "Level",
        "maxPotentialFiltersToShow": 10,
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    # topics
    {
        "key": "id",
        "id": "id",
        "entityType": "topics",
        "subjectEntity": "topics",
        "entityId": "topics",
        "objectEntity": "topics",
        "displayName": "Topic",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "topics",
        "subjectEntity": "topics",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "description",
        "id": "description",
        "entityType": "topics",
        "subjectEntity": "topics",
        "entityId": "topics",
        "objectEntity": "topics",
        "displayName": "description",
        "type": "search",
        "newType": "string",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.description",
    },
    {
        "key": "siblings",
        "id": "siblings",
        "isList": True,
        "entityType": "topics",
        "subjectEntity": "topics",
        "entityId": "topics",
        "objectEntity": "topics",
        "displayName": "related topics (siblings)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.siblings",
    },
    {
        "key": "subfield",
        "id": "subfield",
        "entityType": "topics",
        "subjectEntity": "topics",
        "entityId": "topics",
        "objectEntity": "topics",
        "displayName": "subfield (parent)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.subfield",
    },
    {
        "key": "field",
        "id": "field",
        "entityType": "topics",
        "subjectEntity": "topics",
        "entityId": "topics",
        "objectEntity": "topics",
        "displayName": "field",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.field",
    },
    {
        "key": "domain",
        "id": "domain",
        "entityType": "topics",
        "subjectEntity": "topics",
        "entityId": "topics",
        "objectEntity": "topics",
        "displayName": "domain",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.domain",
    },
    # subfields
    {
        "key": "id",
        "id": "id",
        "entityType": "subfields",
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "Subfield",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "subfields",
        "subjectEntity": "subfields",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "description",
        "id": "description",
        "entityType": "subfields",
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "description",
        "type": "search",
        "newType": "string",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.description",
    },
    {
        "key": "display_name_alternatives",
        "id": "display_name_alternatives",
        "isList": True,
        "entityType": "subfields",
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "alternate names",
        "type": "search",
        "newType": "string",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.display_name_alternatives",
    },
    {
        "key": "topics",
        "id": "topics",
        "isList": True,
        "entityType": "subfields",
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "topics (children)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.topics",
    },
    {
        "key": "siblings",
        "id": "siblings",
        "isList": True,
        "entityType": "subfields",
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "related subfields (siblings)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.siblings",
    },
    {
        "key": "field",
        "id": "field",
        "entityType": "subfields",
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "field (parent)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.field",
    },
    {
        "key": "domain",
        "id": "domain",
        "entityType": "subfields",
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "domain",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.domain",
    },
    # fields
    {
        "key": "id",
        "id": "id",
        "entityType": "fields",
        "subjectEntity": "fields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "Field",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "fields",
        "subjectEntity": "fields",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "description",
        "id": "description",
        "entityType": "fields",
        "subjectEntity": "fields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "description",
        "type": "search",
        "newType": "string",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.description",
    },
    {
        "key": "display_name_alternatives",
        "id": "display_name_alternatives",
        "isList": True,
        "entityType": "fields",
        "subjectEntity": "fields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "alternate names",
        "type": "search",
        "newType": "string",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.display_name_alternatives",
    },
    {
        "key": "siblings",
        "id": "siblings",
        "isList": True,
        "entityType": "fields",
        "subjectEntity": "fields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "related fields (siblings)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.siblings",
    },
    {
        "key": "subfields",
        "id": "subfields",
        "isList": True,
        "entityType": "fields",
        "subjectEntity": "fields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "subfields (children)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.subfields",
    },
    {
        "key": "domain",
        "id": "domain",
        "entityType": "fields",
        "subjectEntity": "fields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "domain (parent)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.domain",
    },
    # domains
    {
        "key": "id",
        "id": "id",
        "entityType": "domains",
        "subjectEntity": "domains",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "Domain",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "domains",
        "subjectEntity": "domains",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "description",
        "id": "description",
        "entityType": "domains",
        "subjectEntity": "domains",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "description",
        "type": "search",
        "newType": "string",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.description",
    },
    {
        "key": "display_name_alternatives",
        "id": "display_name_alternatives",
        "isList": True,
        "entityType": "domains",
        "subjectEntity": "domains",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "alternate names",
        "type": "search",
        "newType": "string",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.display_name_alternatives",
    },
    {
        "key": "fields",
        "id": "fields",
        "isList": True,
        "entityType": "domains",
        "subjectEntity": "domains",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "fields (children)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.fields",
    },
    {
        "key": "siblings",
        "id": "siblings",
        "isList": True,
        "entityType": "domains",
        "subjectEntity": "domains",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "other domains (siblings)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-tag-outline",
        "extractFn": "(e) => e.siblings",
    },
    # types
    {
        "key": "id",
        "id": "id",
        "entityType": "types",
        "subjectEntity": "types",
        "entityId": "types",
        "objectEntity": "types",
        "displayName": "Type",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "types",
        "subjectEntity": "types",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "description",
        "id": "description",
        "entityType": "types",
        "subjectEntity": "types",
        "entityId": "types",
        "objectEntity": "types",
        "displayName": "description",
        "type": "search",
        "newType": "string",
        "icon": "mdi-shape-outline",
        "extractFn": "(e) => e.description",
    },
    {
        "key": "crossref_types",
        "id": "crossref_types",
        "isList": True,
        "entityType": "types",
        "subjectEntity": "types",
        "entityId": "types",
        "objectEntity": "types",
        "displayName": "alternate names (Crossref)",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-shape-outline",
        "extractFn": "(e) => e.crossref_types",
    },
    # countries
    {
        "key": "id",
        "id": "id",
        "entityType": "countries",
        "subjectEntity": "countries",
        "entityId": "countries",
        "objectEntity": "countries",
        "displayName": "Country",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "countries",
        "subjectEntity": "countries",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },
    {
        "key": "countries",
        "id": "countries",
        "isList": True,
        "entityType": "continents",
        "subjectEntity": "continents",
        "entityId": "continents",
        "objectEntity": "continents",
        "displayName": "countries",
        "type": "select",
        "newType": "entity",
        "icon": "mdi-earth",
        "extractFn": "(e) => e.countries",
    },

    # keywords
    {
        "key": "id",
        "id": "id",
        "entityType": "keywords",
        "subjectEntity": "keywords",
        "entityId": "keywords",
        "objectEntity": "keywords",
        "displayName": "Keyword",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "keywords",
        "subjectEntity": "keywords",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },

    # languages
{
        "key": "id",
        "id": "id",
        "entityType": "languages",
        "subjectEntity": "languages",
        "entityId": "languages",
        "objectEntity": "languages",
        "displayName": "Language",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "languages",
        "subjectEntity": "languages",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },

    # licenses
{
        "key": "id",
        "id": "id",
        "entityType": "licenses",
        "subjectEntity": "licenses",
        "entityId": "licenses",
        "objectEntity": "licenses",
        "displayName": "License",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "licenses",
        "subjectEntity": "licenses",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },

    # institution types
{
        "key": "id",
        "id": "id",
        "entityType": "institution-types",
        "subjectEntity": "institution-types",
        "entityId": "institution-types",
        "objectEntity": "institution-types",
        "displayName": "Institution",
        "isId": True,
        "type": "entity",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "institution-types",
        "subjectEntity": "institution-types",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },

    # sdgs
{
        "key": "id",
        "id": "id",
        "entityType": "sdgs",
        "subjectEntity": "sdgs",
        "entityId": "sdgs",
        "objectEntity": "sdgs",
        "displayName": "Sustainable Development Goal",
        "isId": True,
        "type": "entity",
        "actions": ["sort"],
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "key": "display_name",
        "id": "display_name",
        "isColumnMandatory": True,
        "entityType": "sdgs",
        "subjectEntity": "sdgs",
        "displayName": "name",
        "type": "search",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
        "extractFn": "(entity) => entity.display_name",
    },

    # works_count and cited_by_count for authors
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "authors",
        "subjectEntity": "authors",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "authors",
        "subjectEntity": "authors",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for sources
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "sources",
        "subjectEntity": "sources",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for institutions
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "institutions",
        "subjectEntity": "institutions",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for subfields
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "subfields",
        "subjectEntity": "subfields",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "subfields",
        "subjectEntity": "subfields",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for topics
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "topics",
        "subjectEntity": "topics",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "topics",
        "subjectEntity": "topics",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for fields
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "fields",
        "subjectEntity": "fields",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "fields",
        "subjectEntity": "fields",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for domains
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "domains",
        "subjectEntity": "domains",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "domains",
        "subjectEntity": "domains",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for concepts
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "concepts",
        "subjectEntity": "concepts",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "concepts",
        "subjectEntity": "concepts",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for publishers
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "publishers",
        "subjectEntity": "publishers",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "publishers",
        "subjectEntity": "publishers",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for types
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "types",
        "subjectEntity": "types",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "types",
        "subjectEntity": "types",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for funders
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "funders",
        "subjectEntity": "funders",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "funders",
        "subjectEntity": "funders",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for countries
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "countries",
        "subjectEntity": "countries",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "countries",
        "subjectEntity": "countries",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for continents
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "continents",
        "subjectEntity": "continents",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "continents",
        "subjectEntity": "continents",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for institution-types
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "institution-types",
        "subjectEntity": "institution-types",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "institution-types",
        "subjectEntity": "institution-types",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for keywords
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "keywords",
        "subjectEntity": "keywords",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "keywords",
        "subjectEntity": "keywords",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for licenses
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "licenses",
        "subjectEntity": "licenses",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "licenses",
        "subjectEntity": "licenses",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for languages
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "languages",
        "subjectEntity": "languages",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "languages",
        "subjectEntity": "languages",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for sdgs
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "sdgs",
        "subjectEntity": "sdgs",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "sdgs",
        "subjectEntity": "sdgs",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
    # works_count and cited_by_count for source-types
    {
        "key": "works_count",
        "id": "works_count",
        "entityType": "source-types",
        "subjectEntity": "source-types",
        "displayName": "works count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "actions": [
            "filter",
            "sort",
            "column",
        ],
        "actionsPopular": [
            "sort",
            "column",
        ],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.works_count",
    },
    {
        "key": "cited_by_count",
        "id": "cited_by_count",
        "entityType": "source-types",
        "subjectEntity": "source-types",
        "displayName": "citations count",
        "type": "range",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
        "extractFn": "(entity) => entity.cited_by_count",
    },
]

property_configs_dict = {}

for config in property_configs:
    entity_type = config['entityType']
    key = config['key']

    if entity_type not in property_configs_dict:
        property_configs_dict[entity_type] = {}

    property_configs_dict[entity_type][key] = config
