property_configs = [
    # works: WASPFIC.
    {
        "id": "id",
        "subjectEntity": "works",
        "entityId": "works",
        "objectEntity": "works",
        "displayName": "OpenAlex ID",
        "isSingleWork": True,
        "isId": True,
        "newType": "string",
        "category": "ids",
        "actions": [""],
        "icon": "mdi-file-document-outline",
    },
    {
        "id": "doi",
        "subjectEntity": "works",
        "entityId": "works",
        "objectEntity": "works",
        "displayName": "DOI",
        "isSingleWork": True,
        "isId": True,
        "newType": "string",
        "category": "ids",
        "actions": [],
        "icon": "mdi-file-document-outline",
    },
    {
        "id": "concepts.id",
        "isList": True,
        "subjectEntity": "works",
        "displayName": "concept",
        "entityId": "concepts",
        "objectEntity": "concepts",
        "newType": "entity",
        "category": "other",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "primary_topic.id",
        "subjectEntity": "works",
        "displayName": "topic",
        "entityId": "topics",
        "objectEntity": "topics",
        "newType": "entity",
        "category": "other",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "keywords.id",
        "isList": True,
        "subjectEntity": "works",
        "displayName": "keyword",
        "entityId": "keywords",
        "objectEntity": "keywords",
        "newType": "entity",
        "category": "other",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "primary_topic.subfield.id",
        "subjectEntity": "works",
        "displayName": "subfield",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "newType": "entity",
        "category": "other",
        "actions": ["filter", "group_by"],
        "actionsPopular": [],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "primary_topic.field.id",
        "subjectEntity": "works",
        "displayName": "field",
        "entityId": "fields",
        "objectEntity": "fields",
        "newType": "entity",
        "category": "other",
        "actions": ["filter", "group_by"],
        "actionsPopular": [],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "primary_topic.domain.id",
        "subjectEntity": "works",
        "displayName": "domain",
        "entityId": "domains",
        "objectEntity": "domains",
        "newType": "entity",
        "category": "other",
        "actions": ["filter", "group_by"],
        "actionsPopular": [],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "grants.funder",
        "isList": True,
        "subjectEntity": "works",
        "displayName": "funder",
        "entityId": "funders",
        "objectEntity": "funders",
        "newType": "entity",
        "category": "other",
        "actions": ["filter", "group_by"],
        "icon": "mdi-cash-multiple",
    },
    {
        "id": "grants.award_id",
        "isList": True,
        "subjectEntity": "works",
        "displayName": "grant ID",
        "newType": "string",
        "category": "other",
        "actions": [],
        "icon": "mdi-cash-multiple",
    },
    {
        "id": "authorships.institutions.id",
        "isList": True,
        "subjectEntity": "works",
        "displayName": "institution",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "newType": "entity",
        "category": "institution",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-town-hall",
    },
    {
        "id": "authorships.institutions.ror",
        "isList": True,
        "subjectEntity": "works",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "displayName": "ROR ID",
        "isId": True,
        "newType": "string",
        "category": "ids",
        "actions": [],
        "icon": "mdi-town-hall",
    },
    {
        "id": "authorships.author.id",
        "isList": True,
        "subjectEntity": "works",
        "displayName": "author",
        "entityId": "authors",
        "objectEntity": "authors",
        "newType": "entity",
        "category": "author",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-account-outline",
    },
    {
        "id": "authorships.author.orcid",
        "isList": True,
        "subjectEntity": "works",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "ORCID",
        "isId": True,
        "newType": "string",
        "category": "ids",
        "actions": [],
        "icon": "mdi-account-outline",
    },
    {
        "id": "default.search",
        "subjectEntity": "works",
        "displayName": "fulltext",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "category": "other",
        "icon": "mdi-magnify",
    },
    {
        "id": "title_and_abstract.search",
        "subjectEntity": "works",
        "displayName": "title & abstract",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": [],
        "category": "other",
        "icon": "mdi-magnify",
    },
    {
        "id": "display_name.search",
        "subjectEntity": "works",
        "displayName": "title",
        "actions": ["filter"],
        "actionsPopular": [],
        "newType": "string",
        "icon": "mdi-magnify",
    },
    {
        "id": "raw_affiliation_strings.search",
        "subjectEntity": "works",
        "displayName": "raw affiliation string",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": [""],
        "category": "other",
        "icon": "mdi-magnify",
    },
    {
        "id": "doi_starts_with",
        "subjectEntity": "works",
        "displayName": "DOI prefix",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": [],
        "category": "other",
        "icon": "mdi-magnify",
        "verb": "starts with",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "works",
        "displayName": "title",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-file-document-outline",
    },
    {
        "id": "title",
        "isColumnMandatory": False,
        "subjectEntity": "works",
        "displayName": "title",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-file-document-outline",
    },
    {
        "id": "has_abstract",
        "subjectEntity": "works",
        "displayName": "Abstract available",
        "newType": "boolean",
        "actions": ["filter"],
        "icon": "mdi-file-document-outline",
    },
    {
        "id": "authors_count",
        "subjectEntity": "works",
        "displayName": "authors count",
        "newType": "number",
        "sortByValue": True,
        "category": "author",
        "actions": ["filter", "sort", "column"],
        "icon": "mdi-account-outline",
    },
    {
        "id": "corresponding_author_ids",
        "isList": True,
        "subjectEntity": "works",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "corresponding author",
        "newType": "entity",
        "category": "author",
        "actions": ["filter", "group_by"],
        "icon": "mdi-email-outline",
    },
    {
        "id": "open_access.is_oa",
        "subjectEntity": "works",
        "displayName": "open access",
        "newType": "boolean",
        "actions": ["filter", "column", "group_by"],
        "actionsPopular": ["filter", "column", "group_by"],
        "category": "open access",
        "icon": "mdi-lock-open-outline",
    },
    {
        "id": "best_oa_location.license",
        "subjectEntity": "works",
        "entityId": "licenses",
        "displayName": "license",
        "isId": True,
        "newType": "string",
        "actions": ["filter", "column", "group_by"],
        "category": "open access",
        "icon": "mdi-lock-open-outline",
        "displayNullAs": "All rights reserved",
    },
    {
        "id": "open_access.oa_status",
        "subjectEntity": "works",
        "displayName": "Open Access status",
        "newType": "string",
        "actions": [],
        "category": "open access",
        "icon": "mdi-lock-open-outline",
    },
    {
        "id": "best_oa_location.is_accepted",
        "subjectEntity": "works",
        "displayName": "open access accepted",
        "newType": "boolean",
        "actions": ["filter", "column", "group_by"],
        "category": "open access",
        "icon": "mdi-lock-open-outline",
    },
    {
        "id": "best_oa_location.is_published",
        "subjectEntity": "works",
        "displayName": "open access published",
        "newType": "boolean",
        "actions": ["filter", "column", "group_by"],
        "category": "open access",
        "icon": "mdi-lock-open-outline",
    },
    {
        "id": "apc_paid.value_usd",
        "isCurrency": True,
        "subjectEntity": "works",
        "displayName": "APC paid (est)",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter"],
        "icon": "mdi-cash",
    },
    {
        "id": "authorships.countries",
        "isList": True,
        "subjectEntity": "works",
        "entityId": "countries",
        "objectEntity": "countries",
        "displayName": "Country",
        "newType": "entity",
        "isCountry": True,
        "actions": ["filter", "column", "group_by"],
        "actionsPopular": ["group_by"],
        "category": "institution",
        "icon": "mdi-earth",
    },
    {
        "id": "countries_distinct_count",
        "subjectEntity": "works",
        "displayName": "countries count",
        "newType": "number",
        "sortByValue": True,
        "examples": ["1", "2-", "2-10"],
        "actions": ["filter", "sort", "column"],
        "category": "institution",
        "icon": "mdi-earth",
    },
    {
        "id": "institutions_distinct_count",
        "subjectEntity": "works",
        "displayName": "institutions count",
        "newType": "number",
        "sortByValue": True,
        "examples": ["1", "2-", "2-10"],
        "actions": ["filter", "sort", "column"],
        "category": "institution",
        "icon": "mdi-earth",
    },
    {
        "id": "authorships.institutions.continent",
        "isList": True,
        "subjectEntity": "works",
        "entityId": "continents",
        "displayName": "Continent",
        "isId": True,
        "newType": "string",
        "actions": ["filter", "column", "group_by"],
        "actionsPopular": [],
        "icon": "mdi-earth",
    },
    {
        "id": "institutions.is_global_south",
        "subjectEntity": "works",
        "displayName": "from Global South",
        "newType": "boolean",
        "actions": ["filter", "column", "group_by"],
        "category": "institution",
        "icon": "mdi-earth",
    },
    {
        "id": "authorships.institutions.type",
        "isList": True,
        "subjectEntity": "works",
        "entityId": "institution-types",
        "displayName": "institution type",
        "isId": True,
        "category": "institution",
        "newType": "string",
        "actions": ["filter", "group_by"],
        "icon": "mdi-town-hall",
    },
    {
        "id": "corresponding_institution_ids",
        "isList": True,
        "subjectEntity": "works",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "displayName": "corresponding institution",
        "category": "institution",
        "newType": "entity",
        "actions": ["filter", "group_by"],
        "icon": "mdi-email-outline",
    },
    {
        "id": "primary_location.source.id",
        "subjectEntity": "works",
        "displayName": "source",
        "entityId": "sources",
        "objectEntity": "sources",
        "newType": "entity",
        "category": "source",
        "actions": ["filter", "group_by"],
        "icon": "mdi-book-open-outline",
    },
    {
        "id": "primary_location.source.issn",
        "subjectEntity": "works",
        "entityId": "sources",
        "objectEntity": "sources",
        "displayName": "ISSN",
        "isId": True,
        "newType": "string",
        "category": "ids",
        "actions": [],
        "icon": "mdi-book-open-outline",
    },
    {
        "id": "primary_location.source.type",
        "subjectEntity": "works",
        "entityId": "source-types",
        "displayName": "source type",
        "isId": True,
        "newType": "string",
        "category": "source",
        "actions": ["filter", "column", "group_by"],
        "icon": "mdi-book-open-outline",
    },
    {
        "id": "primary_location.source.is_in_doaj",
        "subjectEntity": "works",
        "displayName": "indexed by DOAJ",
        "newType": "boolean",
        "category": "source",
        "actions": ["filter", "group_by"],
        "icon": "mdi-book-open-outline",
    },
    {
        "id": "primary_location.source.is_oa",
        "subjectEntity": "works",
        "displayName": "in OA source",
        "newType": "boolean",
        "category": "source",
        "actions": ["filter", "column", "group_by"],
        "icon": "mdi-book-open-outline",
    },
    {
        "id": "primary_location.source.publisher_lineage",
        "subjectEntity": "works",
        "entityId": "publishers",
        "objectEntity": "publishers",
        "displayName": "publisher",
        "newType": "entity",
        "category": "source",
        "actions": ["filter", "group_by"],
        "icon": "mdi-domain",
    },
    {
        "id": "repository",
        "subjectEntity": "works",
        "displayName": "repository",
        "entityId": "sources",
        "objectEntity": "sources",
        "newType": "entity",
        "category": "source",
        "actions": ["filter", "group_by"],
        "icon": "mdi-book-open-outline",
    },
    {
        "id": "open_access.any_repository_has_fulltext",
        "subjectEntity": "works",
        "displayName": "has repository fulltext",
        "newType": "boolean",
        "category": "source",
        "actions": ["filter", "column", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "type",
        "subjectEntity": "works",
        "entityId": "types",
        "displayName": "type",
        "isExternalId": True,
        "isId": True,
        "externalIdPrefix": "work-types",
        "newType": "string",
        "category": "other",
        "actions": ["filter", "column", "group_by"],
        "actionsPopular": ["filter", "column", "group_by"],
        "icon": "mdi-shape-outline",
    },
    {
        "id": "abstract_inverted_index",
        "subjectEntity": "works",
        "displayName": "Abstract",
        "newType": "string",
        "actions": [],
        "icon": "mdi-text",
    },
    {
        "id": "publication_year",
        "isYear": True,
        "subjectEntity": "works",
        "displayName": "year",
        "isDate": True,
        "newType": "number",
        "sortByValue": True,
        "examples": ["1999", "1999-", "1999-2020"],
        "category": "other",
        "actions": ["filter", "sort", "column", "group_by"],
        "actionsPopular": ["filter", "sort", "column", "group_by"],
        "icon": "mdi-calendar-range",
    },
    {
        "id": "apc_sum",
        "isCurrency": True,
        "subjectEntity": "works",
        "displayName": "APC sum",
        "newType": "sum",
        "category": "other",
        "actions": ["group_by"],
        "actionsPopular": ["group_by"],
        "icon": "mdi-cash",
    },
    {
        "id": "cited_by_count_sum",
        "subjectEntity": "works",
        "displayName": "Citations sum",
        "newType": "sum",
        "category": "other",
        "actions": ["group_by"],
        "actionsPopular": ["group_by"],
        "icon": "mdi-format-quote-close",
    },
    {
        "id": "publication_date",
        "subjectEntity": "works",
        "displayName": "date",
        "isDate": True,
        "newType": "number",
        "actions": ["sort"],
        "sortByValue": True,
        "category": "other",
        "examples": ["1999", "1999-", "1999-2020"],
        "icon": "mdi-calendar-range",
    },
    {
        "id": "has_doi",
        "subjectEntity": "works",
        "displayName": "indexed by Crossref",
        "newType": "boolean",
        "category": "ids",
        "actions": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "mag_only",
        "subjectEntity": "works",
        "displayName": "indexed by MAG only",
        "newType": "boolean",
        "category": "ids",
        "actions": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "has_orcid",
        "subjectEntity": "works",
        "displayName": "indexed by ORCID",
        "newType": "boolean",
        "actions": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "has_pmid",
        "subjectEntity": "works",
        "displayName": "indexed by PubMed",
        "newType": "boolean",
        "category": "ids",
        "actions": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "is_retracted",
        "subjectEntity": "works",
        "displayName": "retracted",
        "newType": "boolean",
        "category": "other",
        "actions": ["filter", "column", "group_by"],
        "icon": "mdi-close-octagon",
    },
    {
        "id": "language",
        "entityId": "languages",
        "subjectEntity": "works",
        "displayName": "language",
        "isId": True,
        "newType": "string",
        "displayNullAs": "Unknown",
        "category": "other",
        "actions": ["filter", "column", "group_by"],
        "actionsPopular": ["column", "group_by"],
        "icon": "mdi-translate",
    },
    {
        "id": "sustainable_development_goals.id",
        "isList": True,
        "entityId": "sdgs",
        "objectEntity": "sdgs",
        "subjectEntity": "works",
        "displayName": "Sustainable Development Goal",
        "newType": "entity",
        "displayNullAs": "Unknown",
        "category": "other",
        "actions": ["filter", "group_by"],
        "icon": "mdi-sprout-outline",
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "works",
        "displayName": "citation count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-format-quote-close",
    },
    {
        "id": "referenced_works_count",
        "subjectEntity": "works",
        "displayName": "references count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column"],
        "actionsPopular": [],
        "icon": "mdi-format-quote-close",
    },
    {
        "id": "cited_by_percentile_year.min",
        "subjectEntity": "works",
        "displayName": "Citation percentile (year)",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-format-quote-close",
    },
    {
        "id": "cited_by",
        "subjectEntity": "works",
        "entityId": "works",
        "objectEntity": "works",
        "displayName": "cited by",
        "isId": True,
        "newType": "string",
        "category": "citation",
        "actions": [],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "referenced_works",
        "subjectEntity": "works",
        "entityId": "works",
        "isList": True,
        "isId": True,
        "objectEntity": "works",
        "displayName": "cites",
        "newType": "string",
        "category": "citation",
        "actions": [],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "related_works",
        "subjectEntity": "works",
        "entityId": "works",
        "objectEntity": "works",
        "displayName": "related to",
        "isList": True,
        "isId": True,
        "newType": "string",
        "category": "other",
        "actions": ["filter"],
        "isHidden": True,
        "icon": "mdi-book-open-outline",
        "isDisplayedAsCount": True,
    },
    # authors
    {
        "id": "id",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "OpenAlex ID",
        "newType": "string",
        "actions": [],
        "actionsPopular": [],
        "isId": True,
        "icon": "mdi-account-outline",
    },
    {
        "id": "ids.orcid",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "ORCID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-account-outline",
    },
    {
        "id": "default.search",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "name",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-magnify",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "authors",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "affiliations.institution.id",
        "isList": True,
        "subjectEntity": "authors",
        "displayName": "Past institutions",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "newType": "entity",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter"],
        "icon": "mdi-town-hall",
    },
    {
        "id": "affiliations.institution.type",
        "isList": True,
        "isId": True,
        "subjectEntity": "authors",
        "entityId": "institution-types",
        "objectEntity": "institution-types",
        "displayName": "Past institutions type",
        "newType": "string",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "id": "last_known_institutions.id",
        "isList": True,
        "subjectEntity": "authors",
        "displayName": "institution",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "newType": "entity",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-town-hall",
    },
    {
        "id": "last_known_institutions.country_code",
        "isList": True,
        "subjectEntity": "authors",
        "entityId": "countries",
        "isId": True,
        "displayName": "institution country",
        "newType": "string",
        "isCountry": True,
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-earth",
    },
    {
        "id": "last_known_institutions.type",
        "isList": True,
        "subjectEntity": "authors",
        "entityId": "institution-types",
        "displayName": "Institution type",
        "isId": True,
        "newType": "string",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "id": "has_orcid",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "Has an ORCID",
        "newType": "boolean",
        "actions": ["filter", "group_by"],
        "actionsPopular": ["filter", "group_by"],
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name_alternatives",
        "isList": True,
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "alternate names",
        "newType": "string",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-town-hall",
    },
    {
        "id": "summary_stats.h_index",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "h-index",
        "newType": "number",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-chart-line",
    },
    {
        "id": "summary_stats.i10_index",
        "subjectEntity": "authors",
        "entityId": "authors",
        "objectEntity": "authors",
        "displayName": "i10-index",
        "newType": "number",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-chart-line",
    },
    # sources
    {
        "id": "id",
        "subjectEntity": "sources",
        "entityId": "sources",
        "objectEntity": "sources",
        "displayName": "OpenAlex ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-book-open-outline",
    },
    {
        "id": "default.search",
        "subjectEntity": "sources",
        "entityId": "sources",
        "objectEntity": "sources",
        "displayName": "name",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-magnify",
    },
    {
        "id": "ids.issn",
        "subjectEntity": "sources",
        "entityId": "sources",
        "displayName": "ISSNs",
        "isId": True,
        "newType": "string",
        "icon": "mdi-book-open-outline",
    },
    {
        "id": "display_name.search",
        "subjectEntity": "sources",
        "displayName": "Title search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "sources",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "publisher",
        "subjectEntity": "sources",
        "entityId": "publishers",
        "objectEntity": "publishers",
        "displayName": "Publisher",
        "newType": "entity",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-domain",
    },
    {
        "id": "id",
        "subjectEntity": "sources-types",
        "entityId": "source-types",
        "objectEntity": "source-types",
        "displayName": "Source Type ID",
        "isId": True,
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "id": "display_name",
        "subjectEntity": "sources-types",
        "entityId": "source-types",
        "objectEntity": "source-types",
        "displayName": "Source type name",
        "newType": "entity",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "id": "description",
        "subjectEntity": "sources-types",
        "entityId": "source-types",
        "objectEntity": "source-types",
        "displayName": "Source type description",
        "newType": "entity",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "id": "type",
        "subjectEntity": "sources",
        "entityId": "source-types",
        "displayName": "Source type",
        "isId": True,
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "id": "apc_usd",
        "isCurrency": True,
        "subjectEntity": "sources",
        "displayName": "Article Processing Charge",
        "newType": "number",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-cash",
    },
    {
        "id": "is_oa",
        "subjectEntity": "sources",
        "displayName": "Fully open access",
        "newType": "boolean",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-lock-open-outline",
    },
    {
        "id": "is_in_doaj",
        "subjectEntity": "sources",
        "displayName": "In DOAJ",
        "newType": "boolean",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-lock-open-outline",
    },
    {
        "id": "alternate_titles",
        "isList": True,
        "subjectEntity": "sources",
        "displayName": "alternate names",
        "newType": "string",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-book-open-outline",
    },
    {
        "id": "summary_stats.2yr_mean_citedness",
        "subjectEntity": "sources",
        "displayName": "2yr mean citedness",
        "newType": "number",
        "actions": ["filter", "sort"],
        "actionsPopular": ["filter", "sort"],
        "icon": "mdi-chart-line",
    },
    {
        "id": "summary_stats.h_index",
        "subjectEntity": "sources",
        "displayName": "h-index",
        "newType": "number",
        "actions": ["filter"],
        "actionsPopular": [],
        "icon": "mdi-chart-line",
    },
    {
        "id": "summary_stats.i10_index",
        "subjectEntity": "sources",
        "displayName": "i10-index",
        "newType": "number",
        "actions": ["filter"],
        "actionsPopular": [],
        "icon": "mdi-chart-line",
    },
    # publishers
    {
        "id": "id",
        "subjectEntity": "publishers",
        "entityId": "publishers",
        "objectEntity": "publishers",
        "displayName": "OpenAlex ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-domain",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "publishers",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "display_name.search",
        "subjectEntity": "publishers",
        "displayName": "Name search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    # funders
    {
        "id": "id",
        "subjectEntity": "funders",
        "entityId": "funders",
        "objectEntity": "funders",
        "displayName": "OpenAlex ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-cash-multiple",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "funders",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "display_name.search",
        "subjectEntity": "funders",
        "displayName": "Name search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    # institutions
    {
        "id": "id",
        "subjectEntity": "institutions",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "displayName": "OpenAlex ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-town-hall",
    },
    {
        "id": "default.search",
        "subjectEntity": "institutions",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "displayName": "name",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-magnify",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "institutions",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "ids.ror",
        "subjectEntity": "institutions",
        "entityId": "institutions",
        "objectEntity": "institutions",
        "displayName": "ROR",
        "isId": True,
        "newType": "string",
        "icon": "mdi-town-hall",
    },
    {
        "id": "display_name.search",
        "subjectEntity": "institutions",
        "displayName": "Name search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    {
        "id": "country_code",
        "subjectEntity": "institutions",
        "entityId": "countries",
        "displayName": "Country",
        "isId": True,
        "newType": "string",
        "isCountry": True,
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-earth",
    },
    {
        "id": "type",
        "subjectEntity": "institutions",
        "entityId": "institution-types",
        "displayName": "Institution type",
        "isId": True,
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "id": "x_concepts.id",
        "isList": True,
        "subjectEntity": "institutions",
        "displayName": "Concepts",
        "entityId": "concepts",
        "objectEntity": "concepts",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name_alternatives",
        "isList": True,
        "subjectEntity": "institutions",
        "displayName": "alternate names",
        "newType": "string",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-town-hall",
    },
    {
        "id": "parent_institutions",
        "isList": True,
        "subjectEntity": "institutions",
        "objectEntity": "institutions",
        "displayName": "parent institutions",
        "newType": "entity",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-town-hall",
    },
    {
        "id": "child_institutions",
        "isList": True,
        "subjectEntity": "institutions",
        "objectEntity": "institutions",
        "displayName": "child institutions",
        "newType": "entity",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-town-hall",
    },
    {
        "id": "related_institutions",
        "isList": True,
        "subjectEntity": "institutions",
        "objectEntity": "institutions",
        "displayName": "related institutions",
        "newType": "entity",
        "actions": [],
        "actionsPopular": [],
        "icon": "mdi-town-hall",
    },
    # institutions: summary_stats
    # none for now.
    # concepts
    {
        "id": "id",
        "subjectEntity": "concepts",
        "entityId": "concepts",
        "objectEntity": "concepts",
        "displayName": "OpenAlex ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "concepts",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "description",
        "subjectEntity": "concepts",
        "entityId": "concepts",
        "objectEntity": "concepts",
        "displayName": "description",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name.search",
        "subjectEntity": "concepts",
        "displayName": "Name search",
        "newType": "string",
        "icon": "mdi-magnify",
    },
    {
        "id": "level",
        "subjectEntity": "concepts",
        "displayName": "Level",
        "maxPotentialFiltersToShow": 10,
        "newType": "number",
        "icon": "mdi-tag-outline",
    },
    # topics
    {
        "id": "id",
        "subjectEntity": "topics",
        "entityId": "topics",
        "objectEntity": "topics",
        "displayName": "OpenAlex ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "topics",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "description",
        "subjectEntity": "topics",
        "entityId": "topics",
        "objectEntity": "topics",
        "displayName": "description",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "siblings",
        "isList": True,
        "subjectEntity": "topics",
        "entityId": "topics",
        "objectEntity": "topics",
        "displayName": "related topics (siblings)",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "subfield",
        "subjectEntity": "topics",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "subfield (parent)",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "field",
        "subjectEntity": "topics",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "field",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "domain",
        "subjectEntity": "topics",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "domain",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    # subfields
    {
        "id": "id",
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "OpenAlex ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "subfields",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "description",
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "description",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name_alternatives",
        "isList": True,
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "alternate names",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "topics",
        "isList": True,
        "subjectEntity": "subfields",
        "entityId": "topics",
        "objectEntity": "topics",
        "displayName": "topics (children)",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "siblings",
        "isList": True,
        "subjectEntity": "subfields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "related subfields (siblings)",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "field",
        "subjectEntity": "subfields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "field (parent)",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "domain",
        "subjectEntity": "subfields",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "domain",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    # fields
    {
        "id": "id",
        "subjectEntity": "fields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "OpenAlex ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "fields",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "description",
        "subjectEntity": "fields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "description",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name_alternatives",
        "isList": True,
        "subjectEntity": "fields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "alternate names",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "siblings",
        "isList": True,
        "subjectEntity": "fields",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "related fields (siblings)",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "subfields",
        "isList": True,
        "subjectEntity": "fields",
        "entityId": "subfields",
        "objectEntity": "subfields",
        "displayName": "subfields (children)",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "domain",
        "subjectEntity": "fields",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "domain (parent)",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    # domains
    {
        "id": "id",
        "subjectEntity": "domains",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "OpenAlex ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "domains",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "description",
        "subjectEntity": "domains",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "description",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name_alternatives",
        "isList": True,
        "subjectEntity": "domains",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "alternate names",
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "fields",
        "isList": True,
        "subjectEntity": "domains",
        "entityId": "fields",
        "objectEntity": "fields",
        "displayName": "fields (children)",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "siblings",
        "isList": True,
        "subjectEntity": "domains",
        "entityId": "domains",
        "objectEntity": "domains",
        "displayName": "other domains (siblings)",
        "newType": "entity",
        "icon": "mdi-tag-outline",
    },
    # types
    {
        "id": "id",
        "subjectEntity": "types",
        "entityId": "types",
        "objectEntity": "types",
        "displayName": "Type ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "types",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "description",
        "subjectEntity": "types",
        "entityId": "types",
        "objectEntity": "types",
        "displayName": "description",
        "newType": "string",
        "icon": "mdi-shape-outline",
    },
    {
        "id": "crossref_types",
        "isList": True,
        "subjectEntity": "types",
        "entityId": "types",
        "displayName": "alternate names (Crossref)",
        "newType": "string",
        "icon": "mdi-shape-outline",
    },
    # countries
    {
        "id": "id",
        "subjectEntity": "countries",
        "entityId": "countries",
        "objectEntity": "countries",
        "displayName": "Country ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "countries",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "id",
        "subjectEntity": "continents",
        "entityId": "continents",
        "isId": True,
        "objectEntity": "continents",
        "displayName": "Continent ID",
        "newType": "string",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "id": "display_name",
        "subjectEntity": "continents",
        "entityId": "continents",
        "objectEntity": "continents",
        "displayName": "Continent name",
        "newType": "entity",
        "actions": ["filter"],
        "actionsPopular": ["filter"],
        "icon": "mdi-shape-outline",
    },
    {
        "id": "countries",
        "isList": True,
        "subjectEntity": "continents",
        "entityId": "continents",
        "objectEntity": "continents",
        "displayName": "countries",
        "newType": "entity",
        "icon": "mdi-earth",
    },
    # keywords
    {
        "id": "id",
        "subjectEntity": "keywords",
        "entityId": "keywords",
        "objectEntity": "keywords",
        "displayName": "Keyword ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "keywords",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    # languages
    {
        "id": "id",
        "subjectEntity": "languages",
        "entityId": "languages",
        "objectEntity": "languages",
        "displayName": "Language ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "languages",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "id",
        "subjectEntity": "licenses",
        "entityId": "licenses",
        "objectEntity": "licenses",
        "displayName": "License ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "licenses",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    {
        "id": "id",
        "subjectEntity": "institution-types",
        "entityId": "institution-types",
        "objectEntity": "institution-types",
        "displayName": "Institution ID",
        "isId": True,
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "institution-types",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    # sdgs
    {
        "id": "id",
        "subjectEntity": "sdgs",
        "entityId": "sdgs",
        "objectEntity": "sdgs",
        "displayName": "SDG ID",
        "isId": True,
        "actions": ["sort"],
        "newType": "string",
        "icon": "mdi-tag-outline",
    },
    {
        "id": "display_name",
        "isColumnMandatory": True,
        "subjectEntity": "sdgs",
        "displayName": "name",
        "newType": "string",
        "actions": ["sort", "column"],
        "actionsPopular": ["sort", "column"],
        "category": "other",
        "icon": "mdi-account-outline",
    },
    # works_count and cited_by_count for authors
    {
        "id": "works_count",
        "subjectEntity": "authors",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "authors",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "sources",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "sources",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "institutions",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "institutions",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "subfields",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "share",
        "subjectEntity": "subfields",
        "displayName": "share",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "subfields",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "topics",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "topics",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "fields",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "fields",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "domains",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "domains",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "concepts",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "concepts",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "publishers",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "publishers",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "types",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "types",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "funders",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "funders",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "countries",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "countries",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "continents",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "continents",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "institution-types",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "institution-types",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "keywords",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "keywords",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "licenses",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "licenses",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "languages",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "languages",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "sdgs",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "sdgs",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
    {
        "id": "works_count",
        "subjectEntity": "source-types",
        "displayName": "works count",
        "newType": "number",
        "sortByValue": True,
        "actions": ["filter", "sort", "column"],
        "actionsPopular": ["sort", "column"],
        "icon": "mdi-file-document-multiple-outline",
        "isDisplayedAsCount": True,
    },
    {
        "id": "cited_by_count",
        "subjectEntity": "source-types",
        "displayName": "citations count",
        "newType": "number",
        "sortByValue": True,
        "category": "citation",
        "actions": ["filter", "column", "sort"],
        "actionsPopular": ["column", "sort"],
        "icon": "mdi-format-quote-close",
        "isDisplayedAsCount": True,
    },
]


property_configs_dict = {}

for config in property_configs:
    entity_type = config["entityType"]
    key = config["key"]

    if entity_type not in property_configs_dict:
        property_configs_dict[entity_type] = {}

    property_configs_dict[entity_type][key] = config
