id: publishers
displayName: publishers
displayNameSingular: publisher
descr: Company hosting journals
descrFull: The publisher of scholarly articles, usually a company or organization.
isNative: true
idRegex: (?i)(?:publishers\/)?(?:https:\/\/openalex\.org\/)?(p\d+)
values: null
