id: sources
displayName: sources
displayNameSingular: source
descr: Journals, conferences, and repositories
descrFull: The source or location of scholarly articles, such as a journal, conference, or repository.
isNative: true
idRegex: (?i)(?:sources\/)?(?:https:\/\/openalex\.org\/)?(s\d+)
values: null
