id: topics
displayName: topics
displayNameSingular: topics
descr: what works are about
descrFull: Topics are the fourth level of description of the subject area of works. Each topic has a unique
  OpenAlex ID. Topics are above keywords but below domains, fields, and subfields in the hierarchy of
  research areas in OpenAlex.
isNative: true
idRegex: (?i)(?:topics\/)?(?:https:\/\/openalex\.org\/)?(t\d+)
values: null
