id: works
displayName: works
displayNameSingular: work
descr: Scholarly papers, books, datasets, etc.
descrFull: Scholarly papers, books, datasets, and other works in OpenAlex.
isNative: true
idRegex: (?i)(?:works\/)?(?:https:\/\/openalex\.org\/)?(w\d+)
