id: work-types
displayName: work types
displayNameSingular: work type
descr: Work type
descrFull: The type of work, such as an article, book, or dataset.
isNative: false
idRegex: (?:https:\/\/openalex\.org\/types\/|types\/)([a-zA-Z\-]+)
values:
- id: types/article
  display_name: article
- id: types/book-chapter
  display_name: book-chapter
- id: types/dataset
  display_name: dataset
- id: types/preprint
  display_name: preprint
- id: types/dissertation
  display_name: dissertation
- id: types/book
  display_name: book
- id: types/review
  display_name: review
- id: types/paratext
  display_name: paratext
- id: types/libguides
  display_name: libguides
- id: types/letter
  display_name: letter
- id: types/other
  display_name: other
- id: types/reference-entry
  display_name: reference-entry
- id: types/report
  display_name: report
- id: types/editorial
  display_name: editorial
- id: types/peer-review
  display_name: peer-review
- id: types/erratum
  display_name: erratum
- id: types/standard
  display_name: standard
- id: types/grant
  display_name: grant
- id: types/supplementary-materials
  display_name: supplementary-materials
- id: types/retraction
  display_name: retraction
